// Code generated by cmd/codegen; DO NOT EDIT.

package protocol

import (
	"encoding/json"
)

type AdditionalFileSystemPermissions struct {
	Read  []AbsolutePathBuf `json:"read,omitempty"`
	Write []AbsolutePathBuf `json:"write,omitempty"`
}

type AdditionalMacOsPermissions struct {
	Accessibility *bool                  `json:"accessibility,omitempty"`
	Automations   *MacOsAutomationValue  `json:"automations,omitempty"`
	Calendar      *bool                  `json:"calendar,omitempty"`
	Preferences   *MacOsPreferencesValue `json:"preferences,omitempty"`
}

type AdditionalPermissionProfile struct {
	FileSystem *AdditionalFileSystemPermissions `json:"fileSystem,omitempty"`
	Macos      *AdditionalMacOsPermissions      `json:"macos,omitempty"`
	Network    *bool                            `json:"network,omitempty"`
}

// AgentStatus Agent lifecycle status, derived from emitted events.
type AgentStatus = json.RawMessage

// CompletedAgentStatus Agent is done. Contains the final assistant message.
type CompletedAgentStatus struct {
	Completed *string `json:"completed"`
}

// ErroredAgentStatus Agent encountered an error.
type ErroredAgentStatus struct {
	Errored string `json:"errored"`
}

type ApplyPatchApprovalParams struct {
	// Use to correlate this with [codex_protocol::protocol::PatchApplyBeginEvent] and [codex_protocol::protocol::PatchApplyEndEvent].
	CallID         string                `json:"callId"`
	ConversationID ThreadID              `json:"conversationId"`
	FileChanges    map[string]FileChange `json:"fileChanges"`
	// When set, the agent is asking the user to allow writes under this root for the remainder of the session (unclear if this is honored today).
	GrantRoot *string `json:"grantRoot,omitempty"`
	// Optional explanatory reason (e.g. request for extra write access).
	Reason *string `json:"reason,omitempty"`
}

type ApplyPatchApprovalResponse struct {
	Decision ReviewDecision `json:"decision"`
}

// CallToolResult The server's response to a tool call.
type CallToolResult struct {
	Content []interface{} `json:"content"`
	IsError *bool         `json:"isError,omitempty"`
}

type ChatgptAuthTokensRefreshParams struct {
	// Workspace/account identifier that Codex was previously using. Clients that manage multiple accounts/workspaces can use this as a hint to refresh the token for the correct workspace. This may be `null` when the prior auth state did not include a workspace identifier (`chatgpt_account_id`).
	PreviousAccountID *string                        `json:"previousAccountId,omitempty"`
	Reason            ChatgptAuthTokensRefreshReason `json:"reason"`
}

type ChatgptAuthTokensRefreshReason = json.RawMessage

type ChatgptAuthTokensRefreshResponse struct {
	AccessToken      string  `json:"accessToken"`
	ChatgptAccountID string  `json:"chatgptAccountId"`
	ChatgptPlanType  *string `json:"chatgptPlanType,omitempty"`
}

type ClientInfo struct {
	Name    string  `json:"name"`
	Title   *string `json:"title,omitempty"`
	Version string  `json:"version"`
}

type CollabAgentRef struct {
	// Optional nickname assigned to an AgentControl-spawned sub-agent.
	AgentNickname *string `json:"agent_nickname,omitempty"`
	// Optional role (agent_role) assigned to an AgentControl-spawned sub-agent.
	AgentRole *string `json:"agent_role,omitempty"`
	// Thread ID of the receiver/new agent.
	ThreadID json.RawMessage `json:"thread_id"`
}

type CollabAgentStatusEntry struct {
	// Optional nickname assigned to an AgentControl-spawned sub-agent.
	AgentNickname *string `json:"agent_nickname,omitempty"`
	// Optional role (agent_role) assigned to an AgentControl-spawned sub-agent.
	AgentRole *string `json:"agent_role,omitempty"`
	// Last known status of the agent.
	Status json.RawMessage `json:"status"`
	// Thread ID of the receiver/new agent.
	ThreadID json.RawMessage `json:"thread_id"`
}

type CommandExecutionApprovalDecision = json.RawMessage

// AcceptWithExecpolicyAmendmentCommandExecutionApprovalDecision User approved the command, and wants to apply the proposed execpolicy amendment so future matching commands can run without prompting.
type AcceptWithExecpolicyAmendmentCommandExecutionApprovalDecision struct {
	AcceptWithExecpolicyAmendment json.RawMessage `json:"acceptWithExecpolicyAmendment"`
}

// ApplyNetworkPolicyAmendmentCommandExecutionApprovalDecision User chose a persistent network policy rule (allow/deny) for this host.
type ApplyNetworkPolicyAmendmentCommandExecutionApprovalDecision struct {
	ApplyNetworkPolicyAmendment json.RawMessage `json:"applyNetworkPolicyAmendment"`
}

type CommandExecutionRequestApprovalParams struct {
	// Unique identifier for this specific approval callback. For regular shell/unified_exec approvals, this is null. For zsh-exec-bridge subcommand approvals, multiple callbacks can belong to one parent `itemId`, so `approvalId` is a distinct opaque callback id (a UUID) used to disambiguate routing.
	ApprovalID *string `json:"approvalId,omitempty"`
	// The command to be executed.
	Command *string `json:"command,omitempty"`
	// Best-effort parsed command actions for friendly display.
	CommandActions []CommandAction `json:"commandActions,omitempty"`
	// The command's working directory.
	Cwd    *string `json:"cwd,omitempty"`
	ItemID string  `json:"itemId"`
	// Optional context for a managed-network approval prompt.
	NetworkApprovalContext *NetworkApprovalContext `json:"networkApprovalContext,omitempty"`
	// Optional proposed execpolicy amendment to allow similar commands without prompting.
	ProposedExecpolicyAmendment []string `json:"proposedExecpolicyAmendment,omitempty"`
	// Optional proposed network policy amendments (allow/deny host) for future requests.
	ProposedNetworkPolicyAmendments []NetworkPolicyAmendment `json:"proposedNetworkPolicyAmendments,omitempty"`
	// Optional explanatory reason (e.g. request for network access).
	Reason   *string `json:"reason,omitempty"`
	ThreadID string  `json:"threadId"`
	TurnID   string  `json:"turnId"`
}

type CommandExecutionRequestApprovalResponse struct {
	Decision CommandExecutionApprovalDecision `json:"decision"`
}

type CustomPrompt struct {
	ArgumentHint *string `json:"argument_hint,omitempty"`
	Content      string  `json:"content"`
	Description  *string `json:"description,omitempty"`
	Name         string  `json:"name"`
	Path         string  `json:"path"`
}

type Duration struct {
	Nanos int64 `json:"nanos"`
	Secs  int64 `json:"secs"`
}

type DynamicToolCallParams struct {
	CallID   string `json:"callId"`
	ThreadID string `json:"threadId"`
	Tool     string `json:"tool"`
	TurnID   string `json:"turnId"`
}

type DynamicToolCallResponse struct {
	ContentItems []DynamicToolCallOutputContentItem `json:"contentItems"`
	Success      bool                               `json:"success"`
}

type ExecCommandApprovalParams struct {
	// Identifier for this specific approval callback.
	ApprovalID *string `json:"approvalId,omitempty"`
	// Use to correlate this with [codex_protocol::protocol::ExecCommandBeginEvent] and [codex_protocol::protocol::ExecCommandEndEvent].
	CallID         string          `json:"callId"`
	Command        []string        `json:"command"`
	ConversationID ThreadID        `json:"conversationId"`
	Cwd            string          `json:"cwd"`
	ParsedCmd      []ParsedCommand `json:"parsedCmd"`
	Reason         *string         `json:"reason,omitempty"`
}

type ExecCommandApprovalResponse struct {
	Decision ReviewDecision `json:"decision"`
}

type ExecCommandSource string

const (
	ExecCommandSourceAgent                  ExecCommandSource = "agent"
	ExecCommandSourceUserShell              ExecCommandSource = "user_shell"
	ExecCommandSourceUnifiedExecStartup     ExecCommandSource = "unified_exec_startup"
	ExecCommandSourceUnifiedExecInteraction ExecCommandSource = "unified_exec_interaction"
)

type ExecCommandStatus string

const (
	ExecCommandStatusCompleted ExecCommandStatus = "completed"
	ExecCommandStatusFailed    ExecCommandStatus = "failed"
	ExecCommandStatusDeclined  ExecCommandStatus = "declined"
)

type ExecOutputStream string

const (
	ExecOutputStreamStdout ExecOutputStream = "stdout"
	ExecOutputStreamStderr ExecOutputStream = "stderr"
)

type FileChangeApprovalDecision = json.RawMessage

type FileChangeRequestApprovalParams struct {
	// [UNSTABLE] When set, the agent is asking the user to allow writes under this root for the remainder of the session (unclear if this is honored today).
	GrantRoot *string `json:"grantRoot,omitempty"`
	ItemID    string  `json:"itemId"`
	// Optional explanatory reason (e.g. request for extra write access).
	Reason   *string `json:"reason,omitempty"`
	ThreadID string  `json:"threadId"`
	TurnID   string  `json:"turnId"`
}

type FileChangeRequestApprovalResponse struct {
	Decision FileChangeApprovalDecision `json:"decision"`
}

type FileSystemPermissions struct {
	Read  []AbsolutePathBuf `json:"read,omitempty"`
	Write []AbsolutePathBuf `json:"write,omitempty"`
}

type FuzzyFileSearchParams struct {
	CancellationToken *string  `json:"cancellationToken,omitempty"`
	Query             string   `json:"query"`
	Roots             []string `json:"roots"`
}

type FuzzyFileSearchResponse struct {
	Files []FuzzyFileSearchResult `json:"files"`
}

// FuzzyFileSearchResult Superset of [`codex_file_search::FileMatch`]
type FuzzyFileSearchResult struct {
	FileName string  `json:"file_name"`
	Indices  []int64 `json:"indices,omitempty"`
	Path     string  `json:"path"`
	Root     string  `json:"root"`
	Score    int64   `json:"score"`
}

type FuzzyFileSearchSessionCompletedNotification struct {
	SessionID string `json:"sessionId"`
}

type FuzzyFileSearchSessionUpdatedNotification struct {
	Files     []FuzzyFileSearchResult `json:"files"`
	Query     string                  `json:"query"`
	SessionID string                  `json:"sessionId"`
}

type HistoryEntry struct {
	ConversationID string `json:"conversation_id"`
	Text           string `json:"text"`
	Ts             int64  `json:"ts"`
}

// InitializeCapabilities Client-declared capabilities negotiated during initialize.
type InitializeCapabilities struct {
	// Opt into receiving experimental API methods and fields.
	ExperimentalAPI *bool `json:"experimentalApi,omitempty"`
	// Exact notification method names that should be suppressed for this connection (for example `codex/event/session_configured`).
	OptOutNotificationMethods []string `json:"optOutNotificationMethods,omitempty"`
}

type InitializeParams struct {
	Capabilities *InitializeCapabilities `json:"capabilities,omitempty"`
	ClientInfo   ClientInfo              `json:"clientInfo"`
}

type InitializeResponse struct {
	UserAgent string `json:"userAgent"`
}

// JSONRPCError A response to a request that indicates an error occurred.
type JSONRPCError struct {
	Error JSONRPCErrorError `json:"error"`
	ID    RequestID         `json:"id"`
}

type JSONRPCErrorError struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

// JSONRPCMessage Refers to any valid JSON-RPC object that can be decoded off the wire, or encoded to be sent.
type JSONRPCMessage = json.RawMessage

// JSONRPCNotification A notification which does not expect a response.
type JSONRPCNotification struct {
	Method string `json:"method"`
}

// JSONRPCRequest A request that expects a response.
type JSONRPCRequest struct {
	ID     RequestID `json:"id"`
	Method string    `json:"method"`
	// Optional W3C Trace Context for distributed tracing.
	Trace *W3cTraceContext `json:"trace,omitempty"`
}

// JSONRPCResponse A successful (non-error) response to a request.
type JSONRPCResponse struct {
	ID RequestID `json:"id"`
}

type MacOsAutomationValue = json.RawMessage

type MacOsPermissions struct {
	Accessibility *bool                  `json:"accessibility,omitempty"`
	Automations   *MacOsAutomationValue  `json:"automations,omitempty"`
	Calendar      *bool                  `json:"calendar,omitempty"`
	Preferences   *MacOsPreferencesValue `json:"preferences,omitempty"`
}

type MacOsPreferencesValue = json.RawMessage

type MCPInvocation struct {
	// Arguments to the tool call.
	Arguments json.RawMessage `json:"arguments,omitempty"`
	// Name of the MCP server as defined in the config.
	Server string `json:"server"`
	// Name of the tool as given by the MCP server.
	Tool string `json:"tool"`
}

type MCPStartupFailure struct {
	Error  string `json:"error"`
	Server string `json:"server"`
}

type MCPStartupStatus = json.RawMessage

type StartingMCPStartupStatus struct {
	State string `json:"state"`
}

type ReadyMCPStartupStatus struct {
	State string `json:"state"`
}

type CancelledMCPStartupStatus struct {
	State string `json:"state"`
}

type NetworkApprovalContext struct {
	Host     string                  `json:"host"`
	Protocol NetworkApprovalProtocol `json:"protocol"`
}

type NetworkApprovalProtocol string

const (
	NetworkApprovalProtocolHttp      NetworkApprovalProtocol = "http"
	NetworkApprovalProtocolHttps     NetworkApprovalProtocol = "https"
	NetworkApprovalProtocolSocks5Tcp NetworkApprovalProtocol = "socks5Tcp"
	NetworkApprovalProtocolSocks5Udp NetworkApprovalProtocol = "socks5Udp"
)

type NetworkPolicyAmendment struct {
	Action NetworkPolicyRuleAction `json:"action"`
	Host   string                  `json:"host"`
}

type NetworkPolicyRuleAction string

const (
	NetworkPolicyRuleActionAllow NetworkPolicyRuleAction = "allow"
	NetworkPolicyRuleActionDeny  NetworkPolicyRuleAction = "deny"
)

type PermissionProfile struct {
	FileSystem *FileSystemPermissions `json:"file_system,omitempty"`
	Macos      *MacOsPermissions      `json:"macos,omitempty"`
	Network    *bool                  `json:"network,omitempty"`
}

type PlanItemArg struct {
	Status StepStatus `json:"status"`
	Step   string     `json:"step"`
}

type RealtimeAudioFrame struct {
	Data              string `json:"data"`
	NumChannels       int64  `json:"num_channels"`
	SampleRate        int64  `json:"sample_rate"`
	SamplesPerChannel *int64 `json:"samples_per_channel,omitempty"`
}

type RealtimeEvent = json.RawMessage

type SessionUpdatedRealtimeEvent struct {
	SessionUpdated json.RawMessage `json:"SessionUpdated"`
}

type AudioOutRealtimeEvent struct {
	AudioOut RealtimeAudioFrame `json:"AudioOut"`
}

type ConversationItemAddedRealtimeEvent struct {
}

type ConversationItemDoneRealtimeEvent struct {
	ConversationItemDone json.RawMessage `json:"ConversationItemDone"`
}

type HandoffRequestedRealtimeEvent struct {
	HandoffRequested RealtimeHandoffRequested `json:"HandoffRequested"`
}

type ErrorRealtimeEvent struct {
	Error string `json:"Error"`
}

type RealtimeHandoffMessage struct {
	Role string `json:"role"`
	Text string `json:"text"`
}

type RealtimeHandoffRequested struct {
	HandoffID       string                   `json:"handoff_id"`
	InputTranscript string                   `json:"input_transcript"`
	ItemID          string                   `json:"item_id"`
	Messages        []RealtimeHandoffMessage `json:"messages"`
}

type RejectConfig struct {
	// Reject MCP elicitation prompts.
	MCPElicitations bool `json:"mcp_elicitations"`
	// Reject prompts triggered by execpolicy `prompt` rules.
	Rules bool `json:"rules"`
	// Reject approval prompts related to sandbox escalation.
	SandboxApproval bool `json:"sandbox_approval"`
}

type RequestID = json.RawMessage

type RequestUserInputQuestion struct {
	Header   string                           `json:"header"`
	ID       string                           `json:"id"`
	IsOther  *bool                            `json:"isOther,omitempty"`
	IsSecret *bool                            `json:"isSecret,omitempty"`
	Options  []RequestUserInputQuestionOption `json:"options,omitempty"`
	Question string                           `json:"question"`
}

type RequestUserInputQuestionOption struct {
	Description string `json:"description"`
	Label       string `json:"label"`
}

type Result_of_CallToolResult_or_String = json.RawMessage

type OkResult_of_CallToolResult_or_String struct {
	Ok CallToolResult `json:"Ok"`
}

type ErrResult_of_CallToolResult_or_String struct {
	Err string `json:"Err"`
}

// ReviewCodeLocation Location of the code related to a review finding.
type ReviewCodeLocation struct {
	AbsoluteFilePath string          `json:"absolute_file_path"`
	LineRange        ReviewLineRange `json:"line_range"`
}

// ReviewDecision User's decision in response to an ExecApprovalRequest.
type ReviewDecision = json.RawMessage

// ApprovedExecpolicyAmendmentReviewDecision User has approved this command and wants to apply the proposed execpolicy amendment so future matching commands are permitted.
type ApprovedExecpolicyAmendmentReviewDecision struct {
	ApprovedExecpolicyAmendment json.RawMessage `json:"approved_execpolicy_amendment"`
}

// NetworkPolicyAmendmentReviewDecision User chose to persist a network policy rule (allow/deny) for future requests to the same host.
type NetworkPolicyAmendmentReviewDecision struct {
	NetworkPolicyAmendment json.RawMessage `json:"network_policy_amendment"`
}

// ReviewFinding A single review finding describing an observed issue or recommendation.
type ReviewFinding struct {
	Body            string             `json:"body"`
	CodeLocation    ReviewCodeLocation `json:"code_location"`
	ConfidenceScore float64            `json:"confidence_score"`
	Priority        int64              `json:"priority"`
	Title           string             `json:"title"`
}

// ReviewLineRange Inclusive line range in a file associated with the finding.
type ReviewLineRange struct {
	End   int64 `json:"end"`
	Start int64 `json:"start"`
}

// ReviewOutputEvent Structured review result produced by a child review session.
type ReviewOutputEvent struct {
	Findings               []ReviewFinding `json:"findings"`
	OverallConfidenceScore float64         `json:"overall_confidence_score"`
	OverallCorrectness     string          `json:"overall_correctness"`
	OverallExplanation     string          `json:"overall_explanation"`
}

type SessionNetworkProxyRuntime struct {
	AdminAddr string `json:"admin_addr"`
	HttpAddr  string `json:"http_addr"`
	SocksAddr string `json:"socks_addr"`
}

type StepStatus string

const (
	StepStatusPending    StepStatus = "pending"
	StepStatusInProgress StepStatus = "in_progress"
	StepStatusCompleted  StepStatus = "completed"
)

type TokenUsage struct {
	CachedInputTokens     int64 `json:"cached_input_tokens"`
	InputTokens           int64 `json:"input_tokens"`
	OutputTokens          int64 `json:"output_tokens"`
	ReasoningOutputTokens int64 `json:"reasoning_output_tokens"`
	TotalTokens           int64 `json:"total_tokens"`
}

type TokenUsageInfo struct {
	LastTokenUsage     TokenUsage `json:"last_token_usage"`
	ModelContextWindow *int64     `json:"model_context_window,omitempty"`
	TotalTokenUsage    TokenUsage `json:"total_token_usage"`
}

// ToolRequestUserInputAnswer EXPERIMENTAL. Captures a user's answer to a request_user_input question.
type ToolRequestUserInputAnswer struct {
	Answers []string `json:"answers"`
}

// ToolRequestUserInputOption EXPERIMENTAL. Defines a single selectable option for request_user_input.
type ToolRequestUserInputOption struct {
	Description string `json:"description"`
	Label       string `json:"label"`
}

// ToolRequestUserInputParams EXPERIMENTAL. Params sent with a request_user_input event.
type ToolRequestUserInputParams struct {
	ItemID    string                         `json:"itemId"`
	Questions []ToolRequestUserInputQuestion `json:"questions"`
	ThreadID  string                         `json:"threadId"`
	TurnID    string                         `json:"turnId"`
}

// ToolRequestUserInputQuestion EXPERIMENTAL. Represents one request_user_input question and its required options.
type ToolRequestUserInputQuestion struct {
	Header   string                       `json:"header"`
	ID       string                       `json:"id"`
	IsOther  *bool                        `json:"isOther,omitempty"`
	IsSecret *bool                        `json:"isSecret,omitempty"`
	Options  []ToolRequestUserInputOption `json:"options,omitempty"`
	Question string                       `json:"question"`
}

// ToolRequestUserInputResponse EXPERIMENTAL. Response payload mapping question ids to answers.
type ToolRequestUserInputResponse struct {
	Answers map[string]ToolRequestUserInputAnswer `json:"answers"`
}

type TurnAbortReason string

const (
	TurnAbortReasonInterrupted TurnAbortReason = "interrupted"
	TurnAbortReasonReplaced    TurnAbortReason = "replaced"
	TurnAbortReasonReviewEnded TurnAbortReason = "review_ended"
)

type W3cTraceContext struct {
	Traceparent *string `json:"traceparent,omitempty"`
	Tracestate  *string `json:"tracestate,omitempty"`
}

// AbsolutePathBuf A path that is guaranteed to be absolute and normalized (though it is not guaranteed to be canonicalized or exist on the filesystem). IMPORTANT: When deserializing an `AbsolutePathBuf`, a base path must be set using [AbsolutePathBufGuard::new]. If no base path is set, the deserialization will fail unless the path being deserialized is already absolute.
type AbsolutePathBuf = string

type AccountLoginCompletedNotification struct {
	Error   *string `json:"error,omitempty"`
	LoginID *string `json:"loginId,omitempty"`
	Success bool    `json:"success"`
}

type AccountRateLimitsUpdatedNotification struct {
	RateLimits RateLimitSnapshot `json:"rateLimits"`
}

type AccountUpdatedNotification struct {
	AuthMode *AuthMode `json:"authMode,omitempty"`
	PlanType *PlanType `json:"planType,omitempty"`
}

type AgentMessageDeltaNotification struct {
	Delta    string `json:"delta"`
	ItemID   string `json:"itemId"`
	ThreadID string `json:"threadId"`
	TurnID   string `json:"turnId"`
}

type AnalyticsConfig struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// AppBranding EXPERIMENTAL - app metadata returned by app-list APIs.
type AppBranding struct {
	Category          *string `json:"category,omitempty"`
	Developer         *string `json:"developer,omitempty"`
	IsDiscoverableApp bool    `json:"isDiscoverableApp"`
	PrivacyPolicy     *string `json:"privacyPolicy,omitempty"`
	TermsOfService    *string `json:"termsOfService,omitempty"`
	Website           *string `json:"website,omitempty"`
}

type AppConfig struct {
	DefaultToolsApprovalMode *AppToolApproval `json:"default_tools_approval_mode,omitempty"`
	DefaultToolsEnabled      *bool            `json:"default_tools_enabled,omitempty"`
	DestructiveEnabled       *bool            `json:"destructive_enabled,omitempty"`
	Enabled                  *bool            `json:"enabled,omitempty"`
	OpenWorldEnabled         *bool            `json:"open_world_enabled,omitempty"`
	Tools                    *AppToolsConfig  `json:"tools,omitempty"`
}

// AppInfo EXPERIMENTAL - app metadata returned by app-list APIs.
type AppInfo struct {
	AppMetadata         *AppMetadata `json:"appMetadata,omitempty"`
	Branding            *AppBranding `json:"branding,omitempty"`
	Description         *string      `json:"description,omitempty"`
	DistributionChannel *string      `json:"distributionChannel,omitempty"`
	ID                  string       `json:"id"`
	InstallURL          *string      `json:"installUrl,omitempty"`
	IsAccessible        *bool        `json:"isAccessible,omitempty"`
	// Whether this app is enabled in config.toml. Example: ```toml [apps.bad_app] enabled = false ```
	IsEnabled   *bool             `json:"isEnabled,omitempty"`
	Labels      map[string]string `json:"labels,omitempty"`
	LogoURL     *string           `json:"logoUrl,omitempty"`
	LogoURLDark *string           `json:"logoUrlDark,omitempty"`
	Name        string            `json:"name"`
}

// AppListUpdatedNotification EXPERIMENTAL - notification emitted when the app list changes.
type AppListUpdatedNotification struct {
	Data []AppInfo `json:"data"`
}

type AppMetadata struct {
	Categories                 []string        `json:"categories,omitempty"`
	Developer                  *string         `json:"developer,omitempty"`
	FirstPartyRequiresInstall  *bool           `json:"firstPartyRequiresInstall,omitempty"`
	FirstPartyType             *string         `json:"firstPartyType,omitempty"`
	Review                     *AppReview      `json:"review,omitempty"`
	Screenshots                []AppScreenshot `json:"screenshots,omitempty"`
	SeoDescription             *string         `json:"seoDescription,omitempty"`
	ShowInComposerWhenUnlinked *bool           `json:"showInComposerWhenUnlinked,omitempty"`
	SubCategories              []string        `json:"subCategories,omitempty"`
	Version                    *string         `json:"version,omitempty"`
	VersionID                  *string         `json:"versionId,omitempty"`
	VersionNotes               *string         `json:"versionNotes,omitempty"`
}

type AppReview struct {
	Status string `json:"status"`
}

type AppScreenshot struct {
	FileID     *string `json:"fileId,omitempty"`
	URL        *string `json:"url,omitempty"`
	UserPrompt string  `json:"userPrompt"`
}

type AppToolApproval string

const (
	AppToolApprovalAuto    AppToolApproval = "auto"
	AppToolApprovalPrompt  AppToolApproval = "prompt"
	AppToolApprovalApprove AppToolApproval = "approve"
)

type AppToolConfig struct {
	ApprovalMode *AppToolApproval `json:"approval_mode,omitempty"`
	Enabled      *bool            `json:"enabled,omitempty"`
}

type AppToolsConfig struct{}

type AppsConfig struct {
	Default *AppsDefaultConfig `json:"_default,omitempty"`
}

type AppsDefaultConfig struct {
	DestructiveEnabled *bool `json:"destructive_enabled,omitempty"`
	Enabled            *bool `json:"enabled,omitempty"`
	OpenWorldEnabled   *bool `json:"open_world_enabled,omitempty"`
}

// AppsListParams EXPERIMENTAL - list available apps/connectors.
type AppsListParams struct {
	// Opaque pagination cursor returned by a previous call.
	Cursor *string `json:"cursor,omitempty"`
	// When true, bypass app caches and fetch the latest data from sources.
	ForceRefetch *bool `json:"forceRefetch,omitempty"`
	// Optional page size; defaults to a reasonable server-side value.
	Limit *int64 `json:"limit,omitempty"`
	// Optional thread id used to evaluate app feature gating from that thread's config.
	ThreadID *string `json:"threadId,omitempty"`
}

// AppsListResponse EXPERIMENTAL - app list response.
type AppsListResponse struct {
	Data []AppInfo `json:"data"`
	// Opaque cursor to pass to the next call to continue after the last item. If None, there are no more items to return.
	NextCursor *string `json:"nextCursor,omitempty"`
}

type AskForApproval = json.RawMessage

type RejectAskForApproval struct {
	Reject json.RawMessage `json:"reject"`
}

// AuthMode Authentication mode for OpenAI-backed providers.
type AuthMode = json.RawMessage

type ByteRange struct {
	End   int64 `json:"end"`
	Start int64 `json:"start"`
}

type CancelLoginAccountParams struct {
	LoginID string `json:"loginId"`
}

type CancelLoginAccountResponse struct {
	Status CancelLoginAccountStatus `json:"status"`
}

type CancelLoginAccountStatus string

const (
	CancelLoginAccountStatusCanceled CancelLoginAccountStatus = "canceled"
	CancelLoginAccountStatusNotFound CancelLoginAccountStatus = "notFound"
)

// CodexErrorInfo This translation layer make sure that we expose codex error code in camel case. When an upstream HTTP status is available (for example, from the Responses API or a provider), it is forwarded in `httpStatusCode` on the relevant `codexErrorInfo` variant.
type CodexErrorInfo = json.RawMessage

type HttpConnectionFailedCodexErrorInfo struct {
	HttpConnectionFailed json.RawMessage `json:"httpConnectionFailed"`
}

// ResponseStreamConnectionFailedCodexErrorInfo Failed to connect to the response SSE stream.
type ResponseStreamConnectionFailedCodexErrorInfo struct {
	ResponseStreamConnectionFailed json.RawMessage `json:"responseStreamConnectionFailed"`
}

// ResponseStreamDisconnectedCodexErrorInfo The response SSE stream disconnected in the middle of a turn before completion.
type ResponseStreamDisconnectedCodexErrorInfo struct {
	ResponseStreamDisconnected json.RawMessage `json:"responseStreamDisconnected"`
}

// ResponseTooManyFailedAttemptsCodexErrorInfo Reached the retry limit for responses.
type ResponseTooManyFailedAttemptsCodexErrorInfo struct {
	ResponseTooManyFailedAttempts json.RawMessage `json:"responseTooManyFailedAttempts"`
}

type CollabAgentState struct {
	Message *string           `json:"message,omitempty"`
	Status  CollabAgentStatus `json:"status"`
}

type CollabAgentStatus string

const (
	CollabAgentStatusPendingInit CollabAgentStatus = "pendingInit"
	CollabAgentStatusRunning     CollabAgentStatus = "running"
	CollabAgentStatusCompleted   CollabAgentStatus = "completed"
	CollabAgentStatusErrored     CollabAgentStatus = "errored"
	CollabAgentStatusShutdown    CollabAgentStatus = "shutdown"
	CollabAgentStatusNotFound    CollabAgentStatus = "notFound"
)

type CollabAgentTool string

const (
	CollabAgentToolSpawnAgent  CollabAgentTool = "spawnAgent"
	CollabAgentToolSendInput   CollabAgentTool = "sendInput"
	CollabAgentToolResumeAgent CollabAgentTool = "resumeAgent"
	CollabAgentToolWait        CollabAgentTool = "wait"
	CollabAgentToolCloseAgent  CollabAgentTool = "closeAgent"
)

type CollabAgentToolCallStatus string

const (
	CollabAgentToolCallStatusInProgress CollabAgentToolCallStatus = "inProgress"
	CollabAgentToolCallStatusCompleted  CollabAgentToolCallStatus = "completed"
	CollabAgentToolCallStatusFailed     CollabAgentToolCallStatus = "failed"
)

// CollaborationMode Collaboration mode for a Codex session.
type CollaborationMode struct {
	Mode     ModeKind `json:"mode"`
	Settings Settings `json:"settings"`
}

// CollaborationModeMask EXPERIMENTAL - collaboration mode preset metadata for clients.
type CollaborationModeMask struct {
	Mode            *ModeKind        `json:"mode,omitempty"`
	Model           *string          `json:"model,omitempty"`
	Name            string           `json:"name"`
	ReasoningEffort *ReasoningEffort `json:"reasoning_effort,omitempty"`
}

type CommandExecParams struct {
	Command       []string       `json:"command"`
	Cwd           *string        `json:"cwd,omitempty"`
	SandboxPolicy *SandboxPolicy `json:"sandboxPolicy,omitempty"`
	TimeoutMs     *int64         `json:"timeoutMs,omitempty"`
}

type CommandExecResponse struct {
	ExitCode int64  `json:"exitCode"`
	Stderr   string `json:"stderr"`
	Stdout   string `json:"stdout"`
}

type CommandExecutionOutputDeltaNotification struct {
	Delta    string `json:"delta"`
	ItemID   string `json:"itemId"`
	ThreadID string `json:"threadId"`
	TurnID   string `json:"turnId"`
}

type CommandExecutionStatus string

const (
	CommandExecutionStatusInProgress CommandExecutionStatus = "inProgress"
	CommandExecutionStatusCompleted  CommandExecutionStatus = "completed"
	CommandExecutionStatusFailed     CommandExecutionStatus = "failed"
	CommandExecutionStatusDeclined   CommandExecutionStatus = "declined"
)

type Config struct {
	Analytics                  *AnalyticsConfig       `json:"analytics,omitempty"`
	ApprovalPolicy             *AskForApproval        `json:"approval_policy,omitempty"`
	CompactPrompt              *string                `json:"compact_prompt,omitempty"`
	DeveloperInstructions      *string                `json:"developer_instructions,omitempty"`
	ForcedChatgptWorkspaceID   *string                `json:"forced_chatgpt_workspace_id,omitempty"`
	ForcedLoginMethod          *ForcedLoginMethod     `json:"forced_login_method,omitempty"`
	Instructions               *string                `json:"instructions,omitempty"`
	Model                      *string                `json:"model,omitempty"`
	ModelAutoCompactTokenLimit *int64                 `json:"model_auto_compact_token_limit,omitempty"`
	ModelContextWindow         *int64                 `json:"model_context_window,omitempty"`
	ModelProvider              *string                `json:"model_provider,omitempty"`
	ModelReasoningEffort       *ReasoningEffort       `json:"model_reasoning_effort,omitempty"`
	ModelReasoningSummary      *ReasoningSummary      `json:"model_reasoning_summary,omitempty"`
	ModelVerbosity             *Verbosity             `json:"model_verbosity,omitempty"`
	Profile                    *string                `json:"profile,omitempty"`
	Profiles                   map[string]ProfileV2   `json:"profiles,omitempty"`
	ReviewModel                *string                `json:"review_model,omitempty"`
	SandboxMode                *SandboxMode           `json:"sandbox_mode,omitempty"`
	SandboxWorkspaceWrite      *SandboxWorkspaceWrite `json:"sandbox_workspace_write,omitempty"`
	ServiceTier                *ServiceTier           `json:"service_tier,omitempty"`
	Tools                      *ToolsV2               `json:"tools,omitempty"`
	WebSearch                  *WebSearchMode         `json:"web_search,omitempty"`
}

type ConfigBatchWriteParams struct {
	Edits           []ConfigEdit `json:"edits"`
	ExpectedVersion *string      `json:"expectedVersion,omitempty"`
	// Path to the config file to write; defaults to the user's `config.toml` when omitted.
	FilePath *string `json:"filePath,omitempty"`
}

type ConfigEdit struct {
	KeyPath       string        `json:"keyPath"`
	MergeStrategy MergeStrategy `json:"mergeStrategy"`
}

type ConfigLayer struct {
	DisabledReason *string           `json:"disabledReason,omitempty"`
	Name           ConfigLayerSource `json:"name"`
	Version        string            `json:"version"`
}

type ConfigLayerMetadata struct {
	Name    ConfigLayerSource `json:"name"`
	Version string            `json:"version"`
}

type ConfigReadParams struct {
	// Optional working directory to resolve project config layers. If specified, return the effective config as seen from that directory (i.e., including any project layers between `cwd` and the project/repo root).
	Cwd           *string `json:"cwd,omitempty"`
	IncludeLayers *bool   `json:"includeLayers,omitempty"`
}

type ConfigReadResponse struct {
	Config  Config                         `json:"config"`
	Layers  []ConfigLayer                  `json:"layers,omitempty"`
	Origins map[string]ConfigLayerMetadata `json:"origins"`
}

type ConfigRequirements struct {
	AllowedApprovalPolicies []AskForApproval      `json:"allowedApprovalPolicies,omitempty"`
	AllowedSandboxModes     []SandboxMode         `json:"allowedSandboxModes,omitempty"`
	AllowedWebSearchModes   []WebSearchMode       `json:"allowedWebSearchModes,omitempty"`
	EnforceResidency        *ResidencyRequirement `json:"enforceResidency,omitempty"`
}

type ConfigRequirementsReadResponse struct {
	// Null if no requirements are configured (e.g. no requirements.toml/MDM entries).
	Requirements *ConfigRequirements `json:"requirements,omitempty"`
}

type ConfigValueWriteParams struct {
	ExpectedVersion *string `json:"expectedVersion,omitempty"`
	// Path to the config file to write; defaults to the user's `config.toml` when omitted.
	FilePath      *string       `json:"filePath,omitempty"`
	KeyPath       string        `json:"keyPath"`
	MergeStrategy MergeStrategy `json:"mergeStrategy"`
}

type ConfigWarningNotification struct {
	// Optional extra guidance or error details.
	Details *string `json:"details,omitempty"`
	// Optional path to the config file that triggered the warning.
	Path *string `json:"path,omitempty"`
	// Optional range for the error location inside the config file.
	Range *TextRange `json:"range,omitempty"`
	// Concise summary of the warning.
	Summary string `json:"summary"`
}

type ConfigWriteResponse struct {
	// Canonical path to the config file that was written.
	FilePath           json.RawMessage     `json:"filePath"`
	OverriddenMetadata *OverriddenMetadata `json:"overriddenMetadata,omitempty"`
	Status             WriteStatus         `json:"status"`
	Version            string              `json:"version"`
}

// ContextCompactedNotification Deprecated: Use `ContextCompaction` item type instead.
type ContextCompactedNotification struct {
	ThreadID string `json:"threadId"`
	TurnID   string `json:"turnId"`
}

type CreditsSnapshot struct {
	Balance    *string `json:"balance,omitempty"`
	HasCredits bool    `json:"hasCredits"`
	Unlimited  bool    `json:"unlimited"`
}

type DeprecationNoticeNotification struct {
	// Optional extra guidance, such as migration steps or rationale.
	Details *string `json:"details,omitempty"`
	// Concise summary of what is deprecated.
	Summary string `json:"summary"`
}

type DynamicToolCallStatus string

const (
	DynamicToolCallStatusInProgress DynamicToolCallStatus = "inProgress"
	DynamicToolCallStatusCompleted  DynamicToolCallStatus = "completed"
	DynamicToolCallStatusFailed     DynamicToolCallStatus = "failed"
)

type DynamicToolSpec struct {
	Description string `json:"description"`
	Name        string `json:"name"`
}

type ErrorNotification struct {
	Error     TurnError `json:"error"`
	ThreadID  string    `json:"threadId"`
	TurnID    string    `json:"turnId"`
	WillRetry bool      `json:"willRetry"`
}

type ExperimentalFeature struct {
	// Announcement copy shown to users when the feature is introduced. Null when this feature is not in beta.
	Announcement *string `json:"announcement,omitempty"`
	// Whether this feature is enabled by default.
	DefaultEnabled bool `json:"defaultEnabled"`
	// Short summary describing what the feature does. Null when this feature is not in beta.
	Description *string `json:"description,omitempty"`
	// User-facing display name shown in the experimental features UI. Null when this feature is not in beta.
	DisplayName *string `json:"displayName,omitempty"`
	// Whether this feature is currently enabled in the loaded config.
	Enabled bool `json:"enabled"`
	// Stable key used in config.toml and CLI flag toggles.
	Name string `json:"name"`
	// Lifecycle stage of this feature flag.
	Stage json.RawMessage `json:"stage"`
}

type ExperimentalFeatureListParams struct {
	// Opaque pagination cursor returned by a previous call.
	Cursor *string `json:"cursor,omitempty"`
	// Optional page size; defaults to a reasonable server-side value.
	Limit *int64 `json:"limit,omitempty"`
}

type ExperimentalFeatureListResponse struct {
	Data []ExperimentalFeature `json:"data"`
	// Opaque cursor to pass to the next call to continue after the last item. If None, there are no more items to return.
	NextCursor *string `json:"nextCursor,omitempty"`
}

type ExperimentalFeatureStage = json.RawMessage

type ExternalAgentConfigDetectParams struct {
	// Zero or more working directories to include for repo-scoped detection.
	Cwds []string `json:"cwds,omitempty"`
	// If true, include detection under the user's home (~/.claude, ~/.codex, etc.).
	IncludeHome *bool `json:"includeHome,omitempty"`
}

type ExternalAgentConfigDetectResponse struct {
	Items []ExternalAgentConfigMigrationItem `json:"items"`
}

type ExternalAgentConfigImportParams struct {
	MigrationItems []ExternalAgentConfigMigrationItem `json:"migrationItems"`
}

type ExternalAgentConfigImportResponse struct{}

type ExternalAgentConfigMigrationItem struct {
	// Null or empty means home-scoped migration; non-empty means repo-scoped migration.
	Cwd         *string                              `json:"cwd,omitempty"`
	Description string                               `json:"description"`
	ItemType    ExternalAgentConfigMigrationItemType `json:"itemType"`
}

type ExternalAgentConfigMigrationItemType string

const (
	ExternalAgentConfigMigrationItemTypeAgentsMd        ExternalAgentConfigMigrationItemType = "AGENTS_MD"
	ExternalAgentConfigMigrationItemTypeCONFIG          ExternalAgentConfigMigrationItemType = "CONFIG"
	ExternalAgentConfigMigrationItemTypeSKILLS          ExternalAgentConfigMigrationItemType = "SKILLS"
	ExternalAgentConfigMigrationItemTypeMcpServerConfig ExternalAgentConfigMigrationItemType = "MCP_SERVER_CONFIG"
)

type FeedbackUploadParams struct {
	Classification string   `json:"classification"`
	ExtraLogFiles  []string `json:"extraLogFiles,omitempty"`
	IncludeLogs    bool     `json:"includeLogs"`
	Reason         *string  `json:"reason,omitempty"`
	ThreadID       *string  `json:"threadId,omitempty"`
}

type FeedbackUploadResponse struct {
	ThreadID string `json:"threadId"`
}

type FileChangeOutputDeltaNotification struct {
	Delta    string `json:"delta"`
	ItemID   string `json:"itemId"`
	ThreadID string `json:"threadId"`
	TurnID   string `json:"turnId"`
}

type FileUpdateChange struct {
	Diff string          `json:"diff"`
	Kind PatchChangeKind `json:"kind"`
	Path string          `json:"path"`
}

type ForcedLoginMethod string

const (
	ForcedLoginMethodChatgpt ForcedLoginMethod = "chatgpt"
	ForcedLoginMethodApi     ForcedLoginMethod = "api"
)

type FunctionCallOutputBody = json.RawMessage

// FunctionCallOutputPayload The payload we send back to OpenAI when reporting a tool call result. `body` serializes directly as the wire value for `function_call_output.output`. `success` remains internal metadata for downstream handling.
type FunctionCallOutputPayload struct {
	Body    FunctionCallOutputBody `json:"body"`
	Success *bool                  `json:"success,omitempty"`
}

type GetAccountParams struct {
	// When `true`, requests a proactive token refresh before returning. In managed auth mode this triggers the normal refresh-token flow. In external auth mode this flag is ignored. Clients should refresh tokens themselves and call `account/login/start` with `chatgptAuthTokens`.
	RefreshToken *bool `json:"refreshToken,omitempty"`
}

type GetAccountRateLimitsResponse struct {
	// Backward-compatible single-bucket view; mirrors the historical payload.
	RateLimits json.RawMessage `json:"rateLimits"`
	// Multi-bucket view keyed by metered `limit_id` (for example, `codex`).
	RateLimitsByLimitID map[string]RateLimitSnapshot `json:"rateLimitsByLimitId,omitempty"`
}

type GetAccountResponse struct {
	Account            *Account `json:"account,omitempty"`
	RequiresOpenaiAuth bool     `json:"requiresOpenaiAuth"`
}

// GhostCommit Details of a ghost commit created from a repository state.
type GhostCommit struct {
	ID                        string   `json:"id"`
	Parent                    *string  `json:"parent,omitempty"`
	PreexistingUntrackedDirs  []string `json:"preexisting_untracked_dirs"`
	PreexistingUntrackedFiles []string `json:"preexisting_untracked_files"`
}

type GitInfo struct {
	Branch    *string `json:"branch,omitempty"`
	OriginURL *string `json:"originUrl,omitempty"`
	Sha       *string `json:"sha,omitempty"`
}

type HazelnutScope string

const (
	HazelnutScopeExample         HazelnutScope = "example"
	HazelnutScopeWorkspaceShared HazelnutScope = "workspace-shared"
	HazelnutScopeAllShared       HazelnutScope = "all-shared"
	HazelnutScopePersonal        HazelnutScope = "personal"
)

// InputModality Canonical user-input modality tags advertised by a model.
type InputModality = json.RawMessage

type ItemCompletedNotification struct {
	Item     ThreadItem `json:"item"`
	ThreadID string     `json:"threadId"`
	TurnID   string     `json:"turnId"`
}

type ItemStartedNotification struct {
	Item     ThreadItem `json:"item"`
	ThreadID string     `json:"threadId"`
	TurnID   string     `json:"turnId"`
}

type ListMCPServerStatusParams struct {
	// Opaque pagination cursor returned by a previous call.
	Cursor *string `json:"cursor,omitempty"`
	// Optional page size; defaults to a server-defined value.
	Limit *int64 `json:"limit,omitempty"`
}

type ListMCPServerStatusResponse struct {
	Data []MCPServerStatus `json:"data"`
	// Opaque cursor to pass to the next call to continue after the last item. If None, there are no more items to return.
	NextCursor *string `json:"nextCursor,omitempty"`
}

type LocalShellStatus string

const (
	LocalShellStatusCompleted  LocalShellStatus = "completed"
	LocalShellStatusInProgress LocalShellStatus = "in_progress"
	LocalShellStatusIncomplete LocalShellStatus = "incomplete"
)

type LogoutAccountResponse struct{}

type MCPAuthStatus string

const (
	MCPAuthStatusUnsupported MCPAuthStatus = "unsupported"
	MCPAuthStatusNotLoggedIn MCPAuthStatus = "notLoggedIn"
	MCPAuthStatusBearerToken MCPAuthStatus = "bearerToken"
	MCPAuthStatusOAuth       MCPAuthStatus = "oAuth"
)

type MCPServerOauthLoginCompletedNotification struct {
	Error   *string `json:"error,omitempty"`
	Name    string  `json:"name"`
	Success bool    `json:"success"`
}

type MCPServerOauthLoginParams struct {
	Name        string   `json:"name"`
	Scopes      []string `json:"scopes,omitempty"`
	TimeoutSecs *int64   `json:"timeoutSecs,omitempty"`
}

type MCPServerOauthLoginResponse struct {
	AuthorizationURL string `json:"authorizationUrl"`
}

type MCPServerRefreshResponse struct{}

type MCPServerStatus struct {
	AuthStatus        MCPAuthStatus      `json:"authStatus"`
	Name              string             `json:"name"`
	ResourceTemplates []ResourceTemplate `json:"resourceTemplates"`
	Resources         []Resource         `json:"resources"`
	Tools             map[string]Tool    `json:"tools"`
}

type MCPToolCallError struct {
	Message string `json:"message"`
}

type MCPToolCallProgressNotification struct {
	ItemID   string `json:"itemId"`
	Message  string `json:"message"`
	ThreadID string `json:"threadId"`
	TurnID   string `json:"turnId"`
}

type MCPToolCallResult struct {
	Content []interface{} `json:"content"`
}

type MCPToolCallStatus string

const (
	MCPToolCallStatusInProgress MCPToolCallStatus = "inProgress"
	MCPToolCallStatusCompleted  MCPToolCallStatus = "completed"
	MCPToolCallStatusFailed     MCPToolCallStatus = "failed"
)

type MergeStrategy string

const (
	MergeStrategyReplace MergeStrategy = "replace"
	MergeStrategyUpsert  MergeStrategy = "upsert"
)

// MessagePhase Classifies an assistant message as interim commentary or final answer text. Providers do not emit this consistently, so callers must treat `None` as "phase unknown" and keep compatibility behavior for legacy models.
type MessagePhase = json.RawMessage

// ModeKind Initial collaboration mode to use when the TUI starts.
type ModeKind string

const (
	ModeKindPlan    ModeKind = "plan"
	ModeKindDefault ModeKind = "default"
)

type Model struct {
	AvailabilityNux           *ModelAvailabilityNux   `json:"availabilityNux,omitempty"`
	DefaultReasoningEffort    ReasoningEffort         `json:"defaultReasoningEffort"`
	Description               string                  `json:"description"`
	DisplayName               string                  `json:"displayName"`
	Hidden                    bool                    `json:"hidden"`
	ID                        string                  `json:"id"`
	InputModalities           []InputModality         `json:"inputModalities,omitempty"`
	IsDefault                 bool                    `json:"isDefault"`
	Model                     string                  `json:"model"`
	SupportedReasoningEfforts []ReasoningEffortOption `json:"supportedReasoningEfforts"`
	SupportsPersonality       *bool                   `json:"supportsPersonality,omitempty"`
	Upgrade                   *string                 `json:"upgrade,omitempty"`
	UpgradeInfo               *ModelUpgradeInfo       `json:"upgradeInfo,omitempty"`
}

type ModelAvailabilityNux struct {
	Message string `json:"message"`
}

type ModelListParams struct {
	// Opaque pagination cursor returned by a previous call.
	Cursor *string `json:"cursor,omitempty"`
	// When true, include models that are hidden from the default picker list.
	IncludeHidden *bool `json:"includeHidden,omitempty"`
	// Optional page size; defaults to a reasonable server-side value.
	Limit *int64 `json:"limit,omitempty"`
}

type ModelListResponse struct {
	Data []Model `json:"data"`
	// Opaque cursor to pass to the next call to continue after the last item. If None, there are no more items to return.
	NextCursor *string `json:"nextCursor,omitempty"`
}

type ModelRerouteReason string

const (
	ModelRerouteReasonHighRiskCyberActivity ModelRerouteReason = "highRiskCyberActivity"
)

type ModelReroutedNotification struct {
	FromModel string             `json:"fromModel"`
	Reason    ModelRerouteReason `json:"reason"`
	ThreadID  string             `json:"threadId"`
	ToModel   string             `json:"toModel"`
	TurnID    string             `json:"turnId"`
}

type ModelUpgradeInfo struct {
	MigrationMarkdown *string `json:"migrationMarkdown,omitempty"`
	Model             string  `json:"model"`
	ModelLink         *string `json:"modelLink,omitempty"`
	UpgradeCopy       *string `json:"upgradeCopy,omitempty"`
}

type NetworkAccess string

const (
	NetworkAccessRestricted NetworkAccess = "restricted"
	NetworkAccessEnabled    NetworkAccess = "enabled"
)

type NetworkRequirements struct {
	AllowLocalBinding                *bool    `json:"allowLocalBinding,omitempty"`
	AllowUnixSockets                 []string `json:"allowUnixSockets,omitempty"`
	AllowUpstreamProxy               *bool    `json:"allowUpstreamProxy,omitempty"`
	AllowedDomains                   []string `json:"allowedDomains,omitempty"`
	DangerouslyAllowAllUnixSockets   *bool    `json:"dangerouslyAllowAllUnixSockets,omitempty"`
	DangerouslyAllowNonLoopbackAdmin *bool    `json:"dangerouslyAllowNonLoopbackAdmin,omitempty"`
	DangerouslyAllowNonLoopbackProxy *bool    `json:"dangerouslyAllowNonLoopbackProxy,omitempty"`
	DeniedDomains                    []string `json:"deniedDomains,omitempty"`
	Enabled                          *bool    `json:"enabled,omitempty"`
	HttpPort                         *int64   `json:"httpPort,omitempty"`
	SocksPort                        *int64   `json:"socksPort,omitempty"`
}

type OverriddenMetadata struct {
	Message         string              `json:"message"`
	OverridingLayer ConfigLayerMetadata `json:"overridingLayer"`
}

type PatchApplyStatus string

const (
	PatchApplyStatusInProgress PatchApplyStatus = "inProgress"
	PatchApplyStatusCompleted  PatchApplyStatus = "completed"
	PatchApplyStatusFailed     PatchApplyStatus = "failed"
	PatchApplyStatusDeclined   PatchApplyStatus = "declined"
)

type Personality string

const (
	PersonalityNone      Personality = "none"
	PersonalityFriendly  Personality = "friendly"
	PersonalityPragmatic Personality = "pragmatic"
)

// PlanDeltaNotification EXPERIMENTAL - proposed plan streaming deltas for plan items. Clients should not assume concatenated deltas match the completed plan item content.
type PlanDeltaNotification struct {
	Delta    string `json:"delta"`
	ItemID   string `json:"itemId"`
	ThreadID string `json:"threadId"`
	TurnID   string `json:"turnId"`
}

type PlanType string

const (
	PlanTypeFree       PlanType = "free"
	PlanTypeGo         PlanType = "go"
	PlanTypePlus       PlanType = "plus"
	PlanTypePro        PlanType = "pro"
	PlanTypeTeam       PlanType = "team"
	PlanTypeBusiness   PlanType = "business"
	PlanTypeEnterprise PlanType = "enterprise"
	PlanTypeEdu        PlanType = "edu"
	PlanTypeUnknown    PlanType = "unknown"
)

type ProductSurface string

const (
	ProductSurfaceChatgpt ProductSurface = "chatgpt"
	ProductSurfaceCodex   ProductSurface = "codex"
	ProductSurfaceApi     ProductSurface = "api"
	ProductSurfaceAtlas   ProductSurface = "atlas"
)

type ProfileV2 struct {
	ApprovalPolicy        *AskForApproval   `json:"approval_policy,omitempty"`
	ChatgptBaseURL        *string           `json:"chatgpt_base_url,omitempty"`
	Model                 *string           `json:"model,omitempty"`
	ModelProvider         *string           `json:"model_provider,omitempty"`
	ModelReasoningEffort  *ReasoningEffort  `json:"model_reasoning_effort,omitempty"`
	ModelReasoningSummary *ReasoningSummary `json:"model_reasoning_summary,omitempty"`
	ModelVerbosity        *Verbosity        `json:"model_verbosity,omitempty"`
	ServiceTier           *ServiceTier      `json:"service_tier,omitempty"`
	WebSearch             *WebSearchMode    `json:"web_search,omitempty"`
}

type RateLimitSnapshot struct {
	Credits   *CreditsSnapshot `json:"credits,omitempty"`
	LimitID   *string          `json:"limitId,omitempty"`
	LimitName *string          `json:"limitName,omitempty"`
	PlanType  *PlanType        `json:"planType,omitempty"`
	Primary   *RateLimitWindow `json:"primary,omitempty"`
	Secondary *RateLimitWindow `json:"secondary,omitempty"`
}

type RateLimitWindow struct {
	ResetsAt           *int64 `json:"resetsAt,omitempty"`
	UsedPercent        int64  `json:"usedPercent"`
	WindowDurationMins *int64 `json:"windowDurationMins,omitempty"`
}

type RawResponseItemCompletedNotification struct {
	Item     ResponseItem `json:"item"`
	ThreadID string       `json:"threadId"`
	TurnID   string       `json:"turnId"`
}

// ReasoningEffort See https://platform.openai.com/docs/guides/reasoning?api-mode=responses#get-started-with-reasoning
type ReasoningEffort string

const (
	ReasoningEffortNone    ReasoningEffort = "none"
	ReasoningEffortMinimal ReasoningEffort = "minimal"
	ReasoningEffortLow     ReasoningEffort = "low"
	ReasoningEffortMedium  ReasoningEffort = "medium"
	ReasoningEffortHigh    ReasoningEffort = "high"
	ReasoningEffortXhigh   ReasoningEffort = "xhigh"
)

type ReasoningEffortOption struct {
	Description     string          `json:"description"`
	ReasoningEffort ReasoningEffort `json:"reasoningEffort"`
}

// ReasoningSummary A summary of the reasoning performed by the model. This can be useful for debugging and understanding the model's reasoning process. See https://platform.openai.com/docs/guides/reasoning?api-mode=responses#reasoning-summaries
type ReasoningSummary = json.RawMessage

type ReasoningSummaryPartAddedNotification struct {
	ItemID       string `json:"itemId"`
	SummaryIndex int64  `json:"summaryIndex"`
	ThreadID     string `json:"threadId"`
	TurnID       string `json:"turnId"`
}

type ReasoningSummaryTextDeltaNotification struct {
	Delta        string `json:"delta"`
	ItemID       string `json:"itemId"`
	SummaryIndex int64  `json:"summaryIndex"`
	ThreadID     string `json:"threadId"`
	TurnID       string `json:"turnId"`
}

type ReasoningTextDeltaNotification struct {
	ContentIndex int64  `json:"contentIndex"`
	Delta        string `json:"delta"`
	ItemID       string `json:"itemId"`
	ThreadID     string `json:"threadId"`
	TurnID       string `json:"turnId"`
}

type RemoteSkillSummary struct {
	Description string `json:"description"`
	ID          string `json:"id"`
	Name        string `json:"name"`
}

type V2RequestID = json.RawMessage

type ResidencyRequirement string

const (
	ResidencyRequirementUs ResidencyRequirement = "us"
)

// Resource A known resource that the server is capable of reading.
type Resource struct {
	Description *string       `json:"description,omitempty"`
	Icons       []interface{} `json:"icons,omitempty"`
	MimeType    *string       `json:"mimeType,omitempty"`
	Name        string        `json:"name"`
	Size        *int64        `json:"size,omitempty"`
	Title       *string       `json:"title,omitempty"`
	Uri         string        `json:"uri"`
}

// ResourceTemplate A template description for resources available on the server.
type ResourceTemplate struct {
	Description *string `json:"description,omitempty"`
	MimeType    *string `json:"mimeType,omitempty"`
	Name        string  `json:"name"`
	Title       *string `json:"title,omitempty"`
	UriTemplate string  `json:"uriTemplate"`
}

type ReviewDelivery string

const (
	ReviewDeliveryInline   ReviewDelivery = "inline"
	ReviewDeliveryDetached ReviewDelivery = "detached"
)

type ReviewStartParams struct {
	// Where to run the review: inline (default) on the current thread or detached on a new thread (returned in `reviewThreadId`).
	Delivery *ReviewDelivery `json:"delivery,omitempty"`
	Target   ReviewTarget    `json:"target"`
	ThreadID string          `json:"threadId"`
}

type ReviewStartResponse struct {
	// Identifies the thread where the review runs. For inline reviews, this is the original thread id. For detached reviews, this is the id of the new review thread.
	ReviewThreadID string `json:"reviewThreadId"`
	Turn           Turn   `json:"turn"`
}

type SandboxMode string

const (
	SandboxModeReadOnly         SandboxMode = "read-only"
	SandboxModeWorkspaceWrite   SandboxMode = "workspace-write"
	SandboxModeDangerFullAccess SandboxMode = "danger-full-access"
)

type SandboxWorkspaceWrite struct {
	ExcludeSlashTmp     *bool    `json:"exclude_slash_tmp,omitempty"`
	ExcludeTmpdirEnvVar *bool    `json:"exclude_tmpdir_env_var,omitempty"`
	NetworkAccess       *bool    `json:"network_access,omitempty"`
	WritableRoots       []string `json:"writable_roots,omitempty"`
}

type ServerRequestResolvedNotification struct {
	RequestID RequestID `json:"requestId"`
	ThreadID  string    `json:"threadId"`
}

type ServiceTier string

const (
	ServiceTierFast ServiceTier = "fast"
)

type SessionSource = json.RawMessage

type SubAgentSessionSource struct {
	SubAgent SubAgentSource `json:"subAgent"`
}

// Settings Settings for a collaboration mode.
type Settings struct {
	DeveloperInstructions *string          `json:"developer_instructions,omitempty"`
	Model                 string           `json:"model"`
	ReasoningEffort       *ReasoningEffort `json:"reasoning_effort,omitempty"`
}

type SkillDependencies struct {
	Tools []SkillToolDependency `json:"tools"`
}

type SkillErrorInfo struct {
	Message string `json:"message"`
	Path    string `json:"path"`
}

type SkillInterface struct {
	BrandColor       *string `json:"brandColor,omitempty"`
	DefaultPrompt    *string `json:"defaultPrompt,omitempty"`
	DisplayName      *string `json:"displayName,omitempty"`
	IconLarge        *string `json:"iconLarge,omitempty"`
	IconSmall        *string `json:"iconSmall,omitempty"`
	ShortDescription *string `json:"shortDescription,omitempty"`
}

type SkillMetadata struct {
	Dependencies *SkillDependencies `json:"dependencies,omitempty"`
	Description  string             `json:"description"`
	Enabled      bool               `json:"enabled"`
	Interface    *SkillInterface    `json:"interface,omitempty"`
	Name         string             `json:"name"`
	Path         string             `json:"path"`
	Scope        SkillScope         `json:"scope"`
	// Legacy short_description from SKILL.md. Prefer SKILL.json interface.short_description.
	ShortDescription *string `json:"shortDescription,omitempty"`
}

type SkillScope string

const (
	SkillScopeUser   SkillScope = "user"
	SkillScopeRepo   SkillScope = "repo"
	SkillScopeSystem SkillScope = "system"
	SkillScopeAdmin  SkillScope = "admin"
)

type SkillToolDependency struct {
	Command     *string `json:"command,omitempty"`
	Description *string `json:"description,omitempty"`
	Transport   *string `json:"transport,omitempty"`
	Type        string  `json:"type"`
	URL         *string `json:"url,omitempty"`
	Value       string  `json:"value"`
}

type SkillsConfigWriteParams struct {
	Enabled bool   `json:"enabled"`
	Path    string `json:"path"`
}

type SkillsConfigWriteResponse struct {
	EffectiveEnabled bool `json:"effectiveEnabled"`
}

type SkillsListEntry struct {
	Cwd    string           `json:"cwd"`
	Errors []SkillErrorInfo `json:"errors"`
	Skills []SkillMetadata  `json:"skills"`
}

type SkillsListExtraRootsForCwd struct {
	Cwd            string   `json:"cwd"`
	ExtraUserRoots []string `json:"extraUserRoots"`
}

type SkillsListParams struct {
	// When empty, defaults to the current session working directory.
	Cwds []string `json:"cwds,omitempty"`
	// When true, bypass the skills cache and re-scan skills from disk.
	ForceReload *bool `json:"forceReload,omitempty"`
	// Optional per-cwd extra roots to scan as user-scoped skills.
	PerCwdExtraUserRoots []SkillsListExtraRootsForCwd `json:"perCwdExtraUserRoots,omitempty"`
}

type SkillsListResponse struct {
	Data []SkillsListEntry `json:"data"`
}

type SkillsRemoteReadParams struct {
	Enabled        *bool           `json:"enabled,omitempty"`
	HazelnutScope  json.RawMessage `json:"hazelnutScope,omitempty"`
	ProductSurface json.RawMessage `json:"productSurface,omitempty"`
}

type SkillsRemoteReadResponse struct {
	Data []RemoteSkillSummary `json:"data"`
}

type SkillsRemoteWriteParams struct {
	HazelnutID string `json:"hazelnutId"`
}

type SkillsRemoteWriteResponse struct {
	ID   string `json:"id"`
	Path string `json:"path"`
}

type SubAgentSource = json.RawMessage

type ThreadSpawnSubAgentSource struct {
	ThreadSpawn json.RawMessage `json:"thread_spawn"`
}

type OtherSubAgentSource struct {
	Other string `json:"other"`
}

type TerminalInteractionNotification struct {
	ItemID    string `json:"itemId"`
	ProcessID string `json:"processId"`
	Stdin     string `json:"stdin"`
	ThreadID  string `json:"threadId"`
	TurnID    string `json:"turnId"`
}

type TextElement struct {
	// Byte range in the parent `text` buffer that this element occupies.
	ByteRange json.RawMessage `json:"byteRange"`
	// Optional human-readable placeholder for the element, displayed in the UI.
	Placeholder *string `json:"placeholder,omitempty"`
}

type TextPosition struct {
	// 1-based column number (in Unicode scalar values).
	Column int64 `json:"column"`
	// 1-based line number.
	Line int64 `json:"line"`
}

type TextRange struct {
	End   TextPosition `json:"end"`
	Start TextPosition `json:"start"`
}

type Thread struct {
	// Optional random unique nickname assigned to an AgentControl-spawned sub-agent.
	AgentNickname *string `json:"agentNickname,omitempty"`
	// Optional role (agent_role) assigned to an AgentControl-spawned sub-agent.
	AgentRole *string `json:"agentRole,omitempty"`
	// Version of the CLI that created the thread.
	CliVersion string `json:"cliVersion"`
	// Unix timestamp (in seconds) when the thread was created.
	CreatedAt int64 `json:"createdAt"`
	// Working directory captured for the thread.
	Cwd string `json:"cwd"`
	// Whether the thread is ephemeral and should not be materialized on disk.
	Ephemeral bool `json:"ephemeral"`
	// Optional Git metadata captured when the thread was created.
	GitInfo *GitInfo `json:"gitInfo,omitempty"`
	ID      string   `json:"id"`
	// Model provider used for this thread (for example, 'openai').
	ModelProvider string `json:"modelProvider"`
	// Optional user-facing thread title.
	Name *string `json:"name,omitempty"`
	// [UNSTABLE] Path to the thread on disk.
	Path *string `json:"path,omitempty"`
	// Usually the first user message in the thread, if available.
	Preview string `json:"preview"`
	// Origin of the thread (CLI, VSCode, codex exec, codex app-server, etc.).
	Source json.RawMessage `json:"source"`
	// Current runtime status for the thread.
	Status json.RawMessage `json:"status"`
	// Only populated on `thread/resume`, `thread/rollback`, `thread/fork`, and `thread/read` (when `includeTurns` is true) responses. For all other responses and notifications returning a Thread, the turns field will be an empty list.
	Turns []Turn `json:"turns"`
	// Unix timestamp (in seconds) when the thread was last updated.
	UpdatedAt int64 `json:"updatedAt"`
}

type ThreadActiveFlag string

const (
	ThreadActiveFlagWaitingOnApproval  ThreadActiveFlag = "waitingOnApproval"
	ThreadActiveFlagWaitingOnUserInput ThreadActiveFlag = "waitingOnUserInput"
)

type ThreadArchiveParams struct {
	ThreadID string `json:"threadId"`
}

type ThreadArchiveResponse struct{}

type ThreadArchivedNotification struct {
	ThreadID string `json:"threadId"`
}

type ThreadClosedNotification struct {
	ThreadID string `json:"threadId"`
}

type ThreadCompactStartParams struct {
	ThreadID string `json:"threadId"`
}

type ThreadCompactStartResponse struct{}

// ThreadForkParams There are two ways to fork a thread: 1. By thread_id: load the thread from disk by thread_id and fork it into a new thread. 2. By path: load the thread from disk by path and fork it into a new thread. If using path, the thread_id param will be ignored. Prefer using thread_id whenever possible.
type ThreadForkParams struct {
	ApprovalPolicy        *AskForApproval        `json:"approvalPolicy,omitempty"`
	BaseInstructions      *string                `json:"baseInstructions,omitempty"`
	Config                map[string]interface{} `json:"config,omitempty"`
	Cwd                   *string                `json:"cwd,omitempty"`
	DeveloperInstructions *string                `json:"developerInstructions,omitempty"`
	// Configuration overrides for the forked thread, if any.
	Model         *string      `json:"model,omitempty"`
	ModelProvider *string      `json:"modelProvider,omitempty"`
	Sandbox       *SandboxMode `json:"sandbox,omitempty"`
	ServiceTier   *ServiceTier `json:"serviceTier,omitempty"`
	ThreadID      string       `json:"threadId"`
}

type ThreadForkResponse struct {
	ApprovalPolicy  AskForApproval   `json:"approvalPolicy"`
	Cwd             string           `json:"cwd"`
	Model           string           `json:"model"`
	ModelProvider   string           `json:"modelProvider"`
	ReasoningEffort *ReasoningEffort `json:"reasoningEffort,omitempty"`
	Sandbox         SandboxPolicy    `json:"sandbox"`
	ServiceTier     *ServiceTier     `json:"serviceTier,omitempty"`
	Thread          Thread           `json:"thread"`
}

type ThreadID = string

type ThreadListParams struct {
	// Optional archived filter; when set to true, only archived threads are returned. If false or null, only non-archived threads are returned.
	Archived *bool `json:"archived,omitempty"`
	// Opaque pagination cursor returned by a previous call.
	Cursor *string `json:"cursor,omitempty"`
	// Optional cwd filter; when set, only threads whose session cwd exactly matches this path are returned.
	Cwd *string `json:"cwd,omitempty"`
	// Optional page size; defaults to a reasonable server-side value.
	Limit *int64 `json:"limit,omitempty"`
	// Optional provider filter; when set, only sessions recorded under these providers are returned. When present but empty, includes all providers.
	ModelProviders []string `json:"modelProviders,omitempty"`
	// Optional substring filter for the extracted thread title.
	SearchTerm *string `json:"searchTerm,omitempty"`
	// Optional sort key; defaults to created_at.
	SortKey *ThreadSortKey `json:"sortKey,omitempty"`
	// Optional source filter; when set, only sessions from these source kinds are returned. When omitted or empty, defaults to interactive sources.
	SourceKinds []ThreadSourceKind `json:"sourceKinds,omitempty"`
}

type ThreadListResponse struct {
	Data []Thread `json:"data"`
	// Opaque cursor to pass to the next call to continue after the last item. if None, there are no more items to return.
	NextCursor *string `json:"nextCursor,omitempty"`
}

type ThreadLoadedListParams struct {
	// Opaque pagination cursor returned by a previous call.
	Cursor *string `json:"cursor,omitempty"`
	// Optional page size; defaults to no limit.
	Limit *int64 `json:"limit,omitempty"`
}

type ThreadLoadedListResponse struct {
	// Thread ids for sessions currently loaded in memory.
	Data []string `json:"data"`
	// Opaque cursor to pass to the next call to continue after the last item. if None, there are no more items to return.
	NextCursor *string `json:"nextCursor,omitempty"`
}

type ThreadNameUpdatedNotification struct {
	ThreadID   string  `json:"threadId"`
	ThreadName *string `json:"threadName,omitempty"`
}

type ThreadReadParams struct {
	// When true, include turns and their items from rollout history.
	IncludeTurns *bool  `json:"includeTurns,omitempty"`
	ThreadID     string `json:"threadId"`
}

type ThreadReadResponse struct {
	Thread Thread `json:"thread"`
}

// ThreadRealtimeAudioChunk EXPERIMENTAL - thread realtime audio chunk.
type ThreadRealtimeAudioChunk struct {
	Data              string `json:"data"`
	NumChannels       int64  `json:"numChannels"`
	SampleRate        int64  `json:"sampleRate"`
	SamplesPerChannel *int64 `json:"samplesPerChannel,omitempty"`
}

// ThreadRealtimeClosedNotification EXPERIMENTAL - emitted when thread realtime transport closes.
type ThreadRealtimeClosedNotification struct {
	Reason   *string `json:"reason,omitempty"`
	ThreadID string  `json:"threadId"`
}

// ThreadRealtimeErrorNotification EXPERIMENTAL - emitted when thread realtime encounters an error.
type ThreadRealtimeErrorNotification struct {
	Message  string `json:"message"`
	ThreadID string `json:"threadId"`
}

// ThreadRealtimeItemAddedNotification EXPERIMENTAL - raw non-audio thread realtime item emitted by the backend.
type ThreadRealtimeItemAddedNotification struct {
	ThreadID string `json:"threadId"`
}

// ThreadRealtimeOutputAudioDeltaNotification EXPERIMENTAL - streamed output audio emitted by thread realtime.
type ThreadRealtimeOutputAudioDeltaNotification struct {
	Audio    ThreadRealtimeAudioChunk `json:"audio"`
	ThreadID string                   `json:"threadId"`
}

// ThreadRealtimeStartedNotification EXPERIMENTAL - emitted when thread realtime startup is accepted.
type ThreadRealtimeStartedNotification struct {
	SessionID *string `json:"sessionId,omitempty"`
	ThreadID  string  `json:"threadId"`
}

// ThreadResumeParams There are three ways to resume a thread: 1. By thread_id: load the thread from disk by thread_id and resume it. 2. By history: instantiate the thread from memory and resume it. 3. By path: load the thread from disk by path and resume it. The precedence is: history > path > thread_id. If using history or path, the thread_id param will be ignored. Prefer using thread_id whenever possible.
type ThreadResumeParams struct {
	ApprovalPolicy        *AskForApproval        `json:"approvalPolicy,omitempty"`
	BaseInstructions      *string                `json:"baseInstructions,omitempty"`
	Config                map[string]interface{} `json:"config,omitempty"`
	Cwd                   *string                `json:"cwd,omitempty"`
	DeveloperInstructions *string                `json:"developerInstructions,omitempty"`
	// Configuration overrides for the resumed thread, if any.
	Model         *string      `json:"model,omitempty"`
	ModelProvider *string      `json:"modelProvider,omitempty"`
	Personality   *Personality `json:"personality,omitempty"`
	Sandbox       *SandboxMode `json:"sandbox,omitempty"`
	ServiceTier   *ServiceTier `json:"serviceTier,omitempty"`
	ThreadID      string       `json:"threadId"`
}

type ThreadResumeResponse struct {
	ApprovalPolicy  AskForApproval   `json:"approvalPolicy"`
	Cwd             string           `json:"cwd"`
	Model           string           `json:"model"`
	ModelProvider   string           `json:"modelProvider"`
	ReasoningEffort *ReasoningEffort `json:"reasoningEffort,omitempty"`
	Sandbox         SandboxPolicy    `json:"sandbox"`
	ServiceTier     *ServiceTier     `json:"serviceTier,omitempty"`
	Thread          Thread           `json:"thread"`
}

type ThreadRollbackParams struct {
	// The number of turns to drop from the end of the thread. Must be >= 1. This only modifies the thread's history and does not revert local file changes that have been made by the agent. Clients are responsible for reverting these changes.
	NumTurns int64  `json:"numTurns"`
	ThreadID string `json:"threadId"`
}

type ThreadRollbackResponse struct {
	// The updated thread after applying the rollback, with `turns` populated. The ThreadItems stored in each Turn are lossy since we explicitly do not persist all agent interactions, such as command executions. This is the same behavior as `thread/resume`.
	Thread json.RawMessage `json:"thread"`
}

type ThreadSetNameParams struct {
	Name     string `json:"name"`
	ThreadID string `json:"threadId"`
}

type ThreadSetNameResponse struct{}

type ThreadSortKey string

const (
	ThreadSortKeyCreatedAt ThreadSortKey = "created_at"
	ThreadSortKeyUpdatedAt ThreadSortKey = "updated_at"
)

type ThreadSourceKind string

const (
	ThreadSourceKindCli                 ThreadSourceKind = "cli"
	ThreadSourceKindVscode              ThreadSourceKind = "vscode"
	ThreadSourceKindExec                ThreadSourceKind = "exec"
	ThreadSourceKindAppServer           ThreadSourceKind = "appServer"
	ThreadSourceKindSubAgent            ThreadSourceKind = "subAgent"
	ThreadSourceKindSubAgentReview      ThreadSourceKind = "subAgentReview"
	ThreadSourceKindSubAgentCompact     ThreadSourceKind = "subAgentCompact"
	ThreadSourceKindSubAgentThreadSpawn ThreadSourceKind = "subAgentThreadSpawn"
	ThreadSourceKindSubAgentOther       ThreadSourceKind = "subAgentOther"
	ThreadSourceKindUnknown             ThreadSourceKind = "unknown"
)

type ThreadStartParams struct {
	ApprovalPolicy        *AskForApproval        `json:"approvalPolicy,omitempty"`
	BaseInstructions      *string                `json:"baseInstructions,omitempty"`
	Config                map[string]interface{} `json:"config,omitempty"`
	Cwd                   *string                `json:"cwd,omitempty"`
	DeveloperInstructions *string                `json:"developerInstructions,omitempty"`
	Ephemeral             *bool                  `json:"ephemeral,omitempty"`
	Model                 *string                `json:"model,omitempty"`
	ModelProvider         *string                `json:"modelProvider,omitempty"`
	Personality           *Personality           `json:"personality,omitempty"`
	Sandbox               *SandboxMode           `json:"sandbox,omitempty"`
	ServiceName           *string                `json:"serviceName,omitempty"`
	ServiceTier           *ServiceTier           `json:"serviceTier,omitempty"`
}

type ThreadStartResponse struct {
	ApprovalPolicy  AskForApproval   `json:"approvalPolicy"`
	Cwd             string           `json:"cwd"`
	Model           string           `json:"model"`
	ModelProvider   string           `json:"modelProvider"`
	ReasoningEffort *ReasoningEffort `json:"reasoningEffort,omitempty"`
	Sandbox         SandboxPolicy    `json:"sandbox"`
	ServiceTier     *ServiceTier     `json:"serviceTier,omitempty"`
	Thread          Thread           `json:"thread"`
}

type ThreadStartedNotification struct {
	Thread Thread `json:"thread"`
}

type ThreadStatusChangedNotification struct {
	Status   ThreadStatus `json:"status"`
	ThreadID string       `json:"threadId"`
}

type ThreadTokenUsage struct {
	Last               TokenUsageBreakdown `json:"last"`
	ModelContextWindow *int64              `json:"modelContextWindow,omitempty"`
	Total              TokenUsageBreakdown `json:"total"`
}

type ThreadTokenUsageUpdatedNotification struct {
	ThreadID   string           `json:"threadId"`
	TokenUsage ThreadTokenUsage `json:"tokenUsage"`
	TurnID     string           `json:"turnId"`
}

type ThreadUnarchiveParams struct {
	ThreadID string `json:"threadId"`
}

type ThreadUnarchiveResponse struct {
	Thread Thread `json:"thread"`
}

type ThreadUnarchivedNotification struct {
	ThreadID string `json:"threadId"`
}

type ThreadUnsubscribeParams struct {
	ThreadID string `json:"threadId"`
}

type ThreadUnsubscribeResponse struct {
	Status ThreadUnsubscribeStatus `json:"status"`
}

type ThreadUnsubscribeStatus string

const (
	ThreadUnsubscribeStatusNotLoaded     ThreadUnsubscribeStatus = "notLoaded"
	ThreadUnsubscribeStatusNotSubscribed ThreadUnsubscribeStatus = "notSubscribed"
	ThreadUnsubscribeStatusUnsubscribed  ThreadUnsubscribeStatus = "unsubscribed"
)

type TokenUsageBreakdown struct {
	CachedInputTokens     int64 `json:"cachedInputTokens"`
	InputTokens           int64 `json:"inputTokens"`
	OutputTokens          int64 `json:"outputTokens"`
	ReasoningOutputTokens int64 `json:"reasoningOutputTokens"`
	TotalTokens           int64 `json:"totalTokens"`
}

// Tool Definition for a tool the client can call.
type Tool struct {
	Description *string       `json:"description,omitempty"`
	Icons       []interface{} `json:"icons,omitempty"`
	Name        string        `json:"name"`
	Title       *string       `json:"title,omitempty"`
}

type ToolsV2 struct {
	ViewImage *bool `json:"view_image,omitempty"`
	WebSearch *bool `json:"web_search,omitempty"`
}

type Turn struct {
	// Only populated when the Turn's status is failed.
	Error *TurnError `json:"error,omitempty"`
	ID    string     `json:"id"`
	// Only populated on a `thread/resume` or `thread/fork` response. For all other responses and notifications returning a Turn, the items field will be an empty list.
	Items  []ThreadItem `json:"items"`
	Status TurnStatus   `json:"status"`
}

type TurnCompletedNotification struct {
	ThreadID string `json:"threadId"`
	Turn     Turn   `json:"turn"`
}

// TurnDiffUpdatedNotification Notification that the turn-level unified diff has changed. Contains the latest aggregated diff across all file changes in the turn.
type TurnDiffUpdatedNotification struct {
	Diff     string `json:"diff"`
	ThreadID string `json:"threadId"`
	TurnID   string `json:"turnId"`
}

type TurnError struct {
	AdditionalDetails *string         `json:"additionalDetails,omitempty"`
	CodexErrorInfo    *CodexErrorInfo `json:"codexErrorInfo,omitempty"`
	Message           string          `json:"message"`
}

type TurnInterruptParams struct {
	ThreadID string `json:"threadId"`
	TurnID   string `json:"turnId"`
}

type TurnInterruptResponse struct{}

type TurnPlanStep struct {
	Status TurnPlanStepStatus `json:"status"`
	Step   string             `json:"step"`
}

type TurnPlanStepStatus string

const (
	TurnPlanStepStatusPending    TurnPlanStepStatus = "pending"
	TurnPlanStepStatusInProgress TurnPlanStepStatus = "inProgress"
	TurnPlanStepStatusCompleted  TurnPlanStepStatus = "completed"
)

type TurnPlanUpdatedNotification struct {
	Explanation *string        `json:"explanation,omitempty"`
	Plan        []TurnPlanStep `json:"plan"`
	ThreadID    string         `json:"threadId"`
	TurnID      string         `json:"turnId"`
}

type TurnStartParams struct {
	// Override the approval policy for this turn and subsequent turns.
	ApprovalPolicy *AskForApproval `json:"approvalPolicy,omitempty"`
	// Override the working directory for this turn and subsequent turns.
	Cwd *string `json:"cwd,omitempty"`
	// Override the reasoning effort for this turn and subsequent turns.
	Effort *ReasoningEffort `json:"effort,omitempty"`
	Input  []UserInput      `json:"input"`
	// Override the model for this turn and subsequent turns.
	Model *string `json:"model,omitempty"`
	// Optional JSON Schema used to constrain the final assistant message for this turn.
	OutputSchema json.RawMessage `json:"outputSchema,omitempty"`
	// Override the personality for this turn and subsequent turns.
	Personality *Personality `json:"personality,omitempty"`
	// Override the sandbox policy for this turn and subsequent turns.
	SandboxPolicy *SandboxPolicy `json:"sandboxPolicy,omitempty"`
	// Override the service tier for this turn and subsequent turns.
	ServiceTier *ServiceTier `json:"serviceTier,omitempty"`
	// Override the reasoning summary for this turn and subsequent turns.
	Summary  *ReasoningSummary `json:"summary,omitempty"`
	ThreadID string            `json:"threadId"`
}

type TurnStartResponse struct {
	Turn Turn `json:"turn"`
}

type TurnStartedNotification struct {
	ThreadID string `json:"threadId"`
	Turn     Turn   `json:"turn"`
}

type TurnStatus string

const (
	TurnStatusCompleted   TurnStatus = "completed"
	TurnStatusInterrupted TurnStatus = "interrupted"
	TurnStatusFailed      TurnStatus = "failed"
	TurnStatusInProgress  TurnStatus = "inProgress"
)

type TurnSteerParams struct {
	// Required active turn id precondition. The request fails when it does not match the currently active turn.
	ExpectedTurnID string      `json:"expectedTurnId"`
	Input          []UserInput `json:"input"`
	ThreadID       string      `json:"threadId"`
}

type TurnSteerResponse struct {
	TurnID string `json:"turnId"`
}

// Verbosity Controls output length/detail on GPT-5 models via the Responses API. Serialized with lowercase values to match the OpenAI API.
type Verbosity string

const (
	VerbosityLow    Verbosity = "low"
	VerbosityMedium Verbosity = "medium"
	VerbosityHigh   Verbosity = "high"
)

type WebSearchMode string

const (
	WebSearchModeDisabled WebSearchMode = "disabled"
	WebSearchModeCached   WebSearchMode = "cached"
	WebSearchModeLive     WebSearchMode = "live"
)

type WindowsSandboxSetupCompletedNotification struct {
	Error   *string                 `json:"error,omitempty"`
	Mode    WindowsSandboxSetupMode `json:"mode"`
	Success bool                    `json:"success"`
}

type WindowsSandboxSetupMode string

const (
	WindowsSandboxSetupModeElevated   WindowsSandboxSetupMode = "elevated"
	WindowsSandboxSetupModeUnelevated WindowsSandboxSetupMode = "unelevated"
)

type WindowsSandboxSetupStartParams struct {
	Mode WindowsSandboxSetupMode `json:"mode"`
}

type WindowsSandboxSetupStartResponse struct {
	Started bool `json:"started"`
}

type WindowsWorldWritableWarningNotification struct {
	ExtraCount  int64    `json:"extraCount"`
	FailedScan  bool     `json:"failedScan"`
	SamplePaths []string `json:"samplePaths"`
}

type WriteStatus string

const (
	WriteStatusOk           WriteStatus = "ok"
	WriteStatusOkOverridden WriteStatus = "okOverridden"
)
