// Code generated by cmd/codegen/main.py; DO NOT EDIT.

package protocol

import (
	"encoding/json"
	"fmt"
)

type ClientNotification struct {
	Method string `json:"method"`
}

// ClientRequest Request from the client to the server.
type ClientRequest struct {
	ID     RequestID       `json:"id"`
	Method string          `json:"method"`
	Params json.RawMessage `json:"params,omitempty"`
}

// InitializeParams unmarshals params for method "initialize".
func (m *ClientRequest) InitializeParams() (*InitializeParams, error) {
	var v InitializeParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal initialize params: %w", err)
	}
	return &v, nil
}

// ThreadStartParams unmarshals params for method "thread/start".
func (m *ClientRequest) ThreadStartParams() (*ThreadStartParams, error) {
	var v ThreadStartParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/start params: %w", err)
	}
	return &v, nil
}

// ThreadResumeParams unmarshals params for method "thread/resume".
func (m *ClientRequest) ThreadResumeParams() (*ThreadResumeParams, error) {
	var v ThreadResumeParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/resume params: %w", err)
	}
	return &v, nil
}

// ThreadForkParams unmarshals params for method "thread/fork".
func (m *ClientRequest) ThreadForkParams() (*ThreadForkParams, error) {
	var v ThreadForkParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/fork params: %w", err)
	}
	return &v, nil
}

// ThreadArchiveParams unmarshals params for method "thread/archive".
func (m *ClientRequest) ThreadArchiveParams() (*ThreadArchiveParams, error) {
	var v ThreadArchiveParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/archive params: %w", err)
	}
	return &v, nil
}

// ThreadUnsubscribeParams unmarshals params for method "thread/unsubscribe".
func (m *ClientRequest) ThreadUnsubscribeParams() (*ThreadUnsubscribeParams, error) {
	var v ThreadUnsubscribeParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/unsubscribe params: %w", err)
	}
	return &v, nil
}

// ThreadNameSetParams unmarshals params for method "thread/name/set".
func (m *ClientRequest) ThreadNameSetParams() (*ThreadSetNameParams, error) {
	var v ThreadSetNameParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/name/set params: %w", err)
	}
	return &v, nil
}

// ThreadUnarchiveParams unmarshals params for method "thread/unarchive".
func (m *ClientRequest) ThreadUnarchiveParams() (*ThreadUnarchiveParams, error) {
	var v ThreadUnarchiveParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/unarchive params: %w", err)
	}
	return &v, nil
}

// ThreadCompactStartParams unmarshals params for method "thread/compact/start".
func (m *ClientRequest) ThreadCompactStartParams() (*ThreadCompactStartParams, error) {
	var v ThreadCompactStartParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/compact/start params: %w", err)
	}
	return &v, nil
}

// ThreadRollbackParams unmarshals params for method "thread/rollback".
func (m *ClientRequest) ThreadRollbackParams() (*ThreadRollbackParams, error) {
	var v ThreadRollbackParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/rollback params: %w", err)
	}
	return &v, nil
}

// ThreadListParams unmarshals params for method "thread/list".
func (m *ClientRequest) ThreadListParams() (*ThreadListParams, error) {
	var v ThreadListParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/list params: %w", err)
	}
	return &v, nil
}

// ThreadLoadedListParams unmarshals params for method "thread/loaded/list".
func (m *ClientRequest) ThreadLoadedListParams() (*ThreadLoadedListParams, error) {
	var v ThreadLoadedListParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/loaded/list params: %w", err)
	}
	return &v, nil
}

// ThreadReadParams unmarshals params for method "thread/read".
func (m *ClientRequest) ThreadReadParams() (*ThreadReadParams, error) {
	var v ThreadReadParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/read params: %w", err)
	}
	return &v, nil
}

// SkillsListParams unmarshals params for method "skills/list".
func (m *ClientRequest) SkillsListParams() (*SkillsListParams, error) {
	var v SkillsListParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal skills/list params: %w", err)
	}
	return &v, nil
}

// SkillsRemoteListParams unmarshals params for method "skills/remote/list".
func (m *ClientRequest) SkillsRemoteListParams() (*SkillsRemoteReadParams, error) {
	var v SkillsRemoteReadParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal skills/remote/list params: %w", err)
	}
	return &v, nil
}

// SkillsRemoteExportParams unmarshals params for method "skills/remote/export".
func (m *ClientRequest) SkillsRemoteExportParams() (*SkillsRemoteWriteParams, error) {
	var v SkillsRemoteWriteParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal skills/remote/export params: %w", err)
	}
	return &v, nil
}

// AppListParams unmarshals params for method "app/list".
func (m *ClientRequest) AppListParams() (*AppsListParams, error) {
	var v AppsListParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal app/list params: %w", err)
	}
	return &v, nil
}

// SkillsConfigWriteParams unmarshals params for method "skills/config/write".
func (m *ClientRequest) SkillsConfigWriteParams() (*SkillsConfigWriteParams, error) {
	var v SkillsConfigWriteParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal skills/config/write params: %w", err)
	}
	return &v, nil
}

// TurnStartParams unmarshals params for method "turn/start".
func (m *ClientRequest) TurnStartParams() (*TurnStartParams, error) {
	var v TurnStartParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal turn/start params: %w", err)
	}
	return &v, nil
}

// TurnSteerParams unmarshals params for method "turn/steer".
func (m *ClientRequest) TurnSteerParams() (*TurnSteerParams, error) {
	var v TurnSteerParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal turn/steer params: %w", err)
	}
	return &v, nil
}

// TurnInterruptParams unmarshals params for method "turn/interrupt".
func (m *ClientRequest) TurnInterruptParams() (*TurnInterruptParams, error) {
	var v TurnInterruptParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal turn/interrupt params: %w", err)
	}
	return &v, nil
}

// ReviewStartParams unmarshals params for method "review/start".
func (m *ClientRequest) ReviewStartParams() (*ReviewStartParams, error) {
	var v ReviewStartParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal review/start params: %w", err)
	}
	return &v, nil
}

// ModelListParams unmarshals params for method "model/list".
func (m *ClientRequest) ModelListParams() (*ModelListParams, error) {
	var v ModelListParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal model/list params: %w", err)
	}
	return &v, nil
}

// ExperimentalFeatureListParams unmarshals params for method "experimentalFeature/list".
func (m *ClientRequest) ExperimentalFeatureListParams() (*ExperimentalFeatureListParams, error) {
	var v ExperimentalFeatureListParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal experimentalFeature/list params: %w", err)
	}
	return &v, nil
}

// McpServerOauthLoginParams unmarshals params for method "mcpServer/oauth/login".
func (m *ClientRequest) McpServerOauthLoginParams() (*MCPServerOauthLoginParams, error) {
	var v MCPServerOauthLoginParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal mcpServer/oauth/login params: %w", err)
	}
	return &v, nil
}

// McpServerStatusListParams unmarshals params for method "mcpServerStatus/list".
func (m *ClientRequest) McpServerStatusListParams() (*ListMCPServerStatusParams, error) {
	var v ListMCPServerStatusParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal mcpServerStatus/list params: %w", err)
	}
	return &v, nil
}

// WindowsSandboxSetupStartParams unmarshals params for method "windowsSandbox/setupStart".
func (m *ClientRequest) WindowsSandboxSetupStartParams() (*WindowsSandboxSetupStartParams, error) {
	var v WindowsSandboxSetupStartParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal windowsSandbox/setupStart params: %w", err)
	}
	return &v, nil
}

// AccountLoginStartParams unmarshals params for method "account/login/start".
func (m *ClientRequest) AccountLoginStartParams() (*LoginAccountParams, error) {
	var v LoginAccountParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal account/login/start params: %w", err)
	}
	return &v, nil
}

// AccountLoginCancelParams unmarshals params for method "account/login/cancel".
func (m *ClientRequest) AccountLoginCancelParams() (*CancelLoginAccountParams, error) {
	var v CancelLoginAccountParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal account/login/cancel params: %w", err)
	}
	return &v, nil
}

// FeedbackUploadParams unmarshals params for method "feedback/upload".
func (m *ClientRequest) FeedbackUploadParams() (*FeedbackUploadParams, error) {
	var v FeedbackUploadParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal feedback/upload params: %w", err)
	}
	return &v, nil
}

// CommandExecParams unmarshals params for method "command/exec".
func (m *ClientRequest) CommandExecParams() (*CommandExecParams, error) {
	var v CommandExecParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal command/exec params: %w", err)
	}
	return &v, nil
}

// ConfigReadParams unmarshals params for method "config/read".
func (m *ClientRequest) ConfigReadParams() (*ConfigReadParams, error) {
	var v ConfigReadParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal config/read params: %w", err)
	}
	return &v, nil
}

// ExternalAgentConfigDetectParams unmarshals params for method "externalAgentConfig/detect".
func (m *ClientRequest) ExternalAgentConfigDetectParams() (*ExternalAgentConfigDetectParams, error) {
	var v ExternalAgentConfigDetectParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal externalAgentConfig/detect params: %w", err)
	}
	return &v, nil
}

// ExternalAgentConfigImportParams unmarshals params for method "externalAgentConfig/import".
func (m *ClientRequest) ExternalAgentConfigImportParams() (*ExternalAgentConfigImportParams, error) {
	var v ExternalAgentConfigImportParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal externalAgentConfig/import params: %w", err)
	}
	return &v, nil
}

// ConfigValueWriteParams unmarshals params for method "config/value/write".
func (m *ClientRequest) ConfigValueWriteParams() (*ConfigValueWriteParams, error) {
	var v ConfigValueWriteParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal config/value/write params: %w", err)
	}
	return &v, nil
}

// ConfigBatchWriteParams unmarshals params for method "config/batchWrite".
func (m *ClientRequest) ConfigBatchWriteParams() (*ConfigBatchWriteParams, error) {
	var v ConfigBatchWriteParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal config/batchWrite params: %w", err)
	}
	return &v, nil
}

// AccountReadParams unmarshals params for method "account/read".
func (m *ClientRequest) AccountReadParams() (*GetAccountParams, error) {
	var v GetAccountParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal account/read params: %w", err)
	}
	return &v, nil
}

// FuzzyFileSearchParams unmarshals params for method "fuzzyFileSearch".
func (m *ClientRequest) FuzzyFileSearchParams() (*FuzzyFileSearchParams, error) {
	var v FuzzyFileSearchParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal fuzzyFileSearch params: %w", err)
	}
	return &v, nil
}

// ServerNotification Notification sent from the server to the client.
type ServerNotification struct {
	Method string          `json:"method"`
	Params json.RawMessage `json:"params,omitempty"`
}

// ErrorParams unmarshals params for method "error".
func (m *ServerNotification) ErrorParams() (*ErrorNotification, error) {
	var v ErrorNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal error params: %w", err)
	}
	return &v, nil
}

// ThreadStartedParams unmarshals params for method "thread/started".
func (m *ServerNotification) ThreadStartedParams() (*ThreadStartedNotification, error) {
	var v ThreadStartedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/started params: %w", err)
	}
	return &v, nil
}

// ThreadStatusChangedParams unmarshals params for method "thread/status/changed".
func (m *ServerNotification) ThreadStatusChangedParams() (*ThreadStatusChangedNotification, error) {
	var v ThreadStatusChangedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/status/changed params: %w", err)
	}
	return &v, nil
}

// ThreadArchivedParams unmarshals params for method "thread/archived".
func (m *ServerNotification) ThreadArchivedParams() (*ThreadArchivedNotification, error) {
	var v ThreadArchivedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/archived params: %w", err)
	}
	return &v, nil
}

// ThreadUnarchivedParams unmarshals params for method "thread/unarchived".
func (m *ServerNotification) ThreadUnarchivedParams() (*ThreadUnarchivedNotification, error) {
	var v ThreadUnarchivedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/unarchived params: %w", err)
	}
	return &v, nil
}

// ThreadClosedParams unmarshals params for method "thread/closed".
func (m *ServerNotification) ThreadClosedParams() (*ThreadClosedNotification, error) {
	var v ThreadClosedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/closed params: %w", err)
	}
	return &v, nil
}

// ThreadNameUpdatedParams unmarshals params for method "thread/name/updated".
func (m *ServerNotification) ThreadNameUpdatedParams() (*ThreadNameUpdatedNotification, error) {
	var v ThreadNameUpdatedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/name/updated params: %w", err)
	}
	return &v, nil
}

// ThreadTokenUsageUpdatedParams unmarshals params for method "thread/tokenUsage/updated".
func (m *ServerNotification) ThreadTokenUsageUpdatedParams() (*ThreadTokenUsageUpdatedNotification, error) {
	var v ThreadTokenUsageUpdatedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/tokenUsage/updated params: %w", err)
	}
	return &v, nil
}

// TurnStartedParams unmarshals params for method "turn/started".
func (m *ServerNotification) TurnStartedParams() (*TurnStartedNotification, error) {
	var v TurnStartedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal turn/started params: %w", err)
	}
	return &v, nil
}

// TurnCompletedParams unmarshals params for method "turn/completed".
func (m *ServerNotification) TurnCompletedParams() (*TurnCompletedNotification, error) {
	var v TurnCompletedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal turn/completed params: %w", err)
	}
	return &v, nil
}

// TurnDiffUpdatedParams unmarshals params for method "turn/diff/updated".
func (m *ServerNotification) TurnDiffUpdatedParams() (*TurnDiffUpdatedNotification, error) {
	var v TurnDiffUpdatedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal turn/diff/updated params: %w", err)
	}
	return &v, nil
}

// TurnPlanUpdatedParams unmarshals params for method "turn/plan/updated".
func (m *ServerNotification) TurnPlanUpdatedParams() (*TurnPlanUpdatedNotification, error) {
	var v TurnPlanUpdatedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal turn/plan/updated params: %w", err)
	}
	return &v, nil
}

// ItemStartedParams unmarshals params for method "item/started".
func (m *ServerNotification) ItemStartedParams() (*ItemStartedNotification, error) {
	var v ItemStartedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal item/started params: %w", err)
	}
	return &v, nil
}

// ItemCompletedParams unmarshals params for method "item/completed".
func (m *ServerNotification) ItemCompletedParams() (*ItemCompletedNotification, error) {
	var v ItemCompletedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal item/completed params: %w", err)
	}
	return &v, nil
}

// ItemAgentMessageDeltaParams unmarshals params for method "item/agentMessage/delta".
func (m *ServerNotification) ItemAgentMessageDeltaParams() (*AgentMessageDeltaNotification, error) {
	var v AgentMessageDeltaNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal item/agentMessage/delta params: %w", err)
	}
	return &v, nil
}

// ItemPlanDeltaParams unmarshals params for method "item/plan/delta".
func (m *ServerNotification) ItemPlanDeltaParams() (*PlanDeltaNotification, error) {
	var v PlanDeltaNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal item/plan/delta params: %w", err)
	}
	return &v, nil
}

// ItemCommandExecutionOutputDeltaParams unmarshals params for method "item/commandExecution/outputDelta".
func (m *ServerNotification) ItemCommandExecutionOutputDeltaParams() (*CommandExecutionOutputDeltaNotification, error) {
	var v CommandExecutionOutputDeltaNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal item/commandExecution/outputDelta params: %w", err)
	}
	return &v, nil
}

// ItemCommandExecutionTerminalInteractionParams unmarshals params for method "item/commandExecution/terminalInteraction".
func (m *ServerNotification) ItemCommandExecutionTerminalInteractionParams() (*TerminalInteractionNotification, error) {
	var v TerminalInteractionNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal item/commandExecution/terminalInteraction params: %w", err)
	}
	return &v, nil
}

// ItemFileChangeOutputDeltaParams unmarshals params for method "item/fileChange/outputDelta".
func (m *ServerNotification) ItemFileChangeOutputDeltaParams() (*FileChangeOutputDeltaNotification, error) {
	var v FileChangeOutputDeltaNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal item/fileChange/outputDelta params: %w", err)
	}
	return &v, nil
}

// ServerRequestResolvedParams unmarshals params for method "serverRequest/resolved".
func (m *ServerNotification) ServerRequestResolvedParams() (*ServerRequestResolvedNotification, error) {
	var v ServerRequestResolvedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal serverRequest/resolved params: %w", err)
	}
	return &v, nil
}

// ItemMcpToolCallProgressParams unmarshals params for method "item/mcpToolCall/progress".
func (m *ServerNotification) ItemMcpToolCallProgressParams() (*MCPToolCallProgressNotification, error) {
	var v MCPToolCallProgressNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal item/mcpToolCall/progress params: %w", err)
	}
	return &v, nil
}

// McpServerOauthLoginCompletedParams unmarshals params for method "mcpServer/oauthLogin/completed".
func (m *ServerNotification) McpServerOauthLoginCompletedParams() (*MCPServerOauthLoginCompletedNotification, error) {
	var v MCPServerOauthLoginCompletedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal mcpServer/oauthLogin/completed params: %w", err)
	}
	return &v, nil
}

// AccountUpdatedParams unmarshals params for method "account/updated".
func (m *ServerNotification) AccountUpdatedParams() (*AccountUpdatedNotification, error) {
	var v AccountUpdatedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal account/updated params: %w", err)
	}
	return &v, nil
}

// AccountRateLimitsUpdatedParams unmarshals params for method "account/rateLimits/updated".
func (m *ServerNotification) AccountRateLimitsUpdatedParams() (*AccountRateLimitsUpdatedNotification, error) {
	var v AccountRateLimitsUpdatedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal account/rateLimits/updated params: %w", err)
	}
	return &v, nil
}

// AppListUpdatedParams unmarshals params for method "app/list/updated".
func (m *ServerNotification) AppListUpdatedParams() (*AppListUpdatedNotification, error) {
	var v AppListUpdatedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal app/list/updated params: %w", err)
	}
	return &v, nil
}

// ItemReasoningSummaryTextDeltaParams unmarshals params for method "item/reasoning/summaryTextDelta".
func (m *ServerNotification) ItemReasoningSummaryTextDeltaParams() (*ReasoningSummaryTextDeltaNotification, error) {
	var v ReasoningSummaryTextDeltaNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal item/reasoning/summaryTextDelta params: %w", err)
	}
	return &v, nil
}

// ItemReasoningSummaryPartAddedParams unmarshals params for method "item/reasoning/summaryPartAdded".
func (m *ServerNotification) ItemReasoningSummaryPartAddedParams() (*ReasoningSummaryPartAddedNotification, error) {
	var v ReasoningSummaryPartAddedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal item/reasoning/summaryPartAdded params: %w", err)
	}
	return &v, nil
}

// ItemReasoningTextDeltaParams unmarshals params for method "item/reasoning/textDelta".
func (m *ServerNotification) ItemReasoningTextDeltaParams() (*ReasoningTextDeltaNotification, error) {
	var v ReasoningTextDeltaNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal item/reasoning/textDelta params: %w", err)
	}
	return &v, nil
}

// ThreadCompactedParams unmarshals params for method "thread/compacted".
func (m *ServerNotification) ThreadCompactedParams() (*ContextCompactedNotification, error) {
	var v ContextCompactedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/compacted params: %w", err)
	}
	return &v, nil
}

// ModelReroutedParams unmarshals params for method "model/rerouted".
func (m *ServerNotification) ModelReroutedParams() (*ModelReroutedNotification, error) {
	var v ModelReroutedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal model/rerouted params: %w", err)
	}
	return &v, nil
}

// DeprecationNoticeParams unmarshals params for method "deprecationNotice".
func (m *ServerNotification) DeprecationNoticeParams() (*DeprecationNoticeNotification, error) {
	var v DeprecationNoticeNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal deprecationNotice params: %w", err)
	}
	return &v, nil
}

// ConfigWarningParams unmarshals params for method "configWarning".
func (m *ServerNotification) ConfigWarningParams() (*ConfigWarningNotification, error) {
	var v ConfigWarningNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal configWarning params: %w", err)
	}
	return &v, nil
}

// FuzzyFileSearchSessionUpdatedParams unmarshals params for method "fuzzyFileSearch/sessionUpdated".
func (m *ServerNotification) FuzzyFileSearchSessionUpdatedParams() (*FuzzyFileSearchSessionUpdatedNotification, error) {
	var v FuzzyFileSearchSessionUpdatedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal fuzzyFileSearch/sessionUpdated params: %w", err)
	}
	return &v, nil
}

// FuzzyFileSearchSessionCompletedParams unmarshals params for method "fuzzyFileSearch/sessionCompleted".
func (m *ServerNotification) FuzzyFileSearchSessionCompletedParams() (*FuzzyFileSearchSessionCompletedNotification, error) {
	var v FuzzyFileSearchSessionCompletedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal fuzzyFileSearch/sessionCompleted params: %w", err)
	}
	return &v, nil
}

// ThreadRealtimeStartedParams unmarshals params for method "thread/realtime/started".
func (m *ServerNotification) ThreadRealtimeStartedParams() (*ThreadRealtimeStartedNotification, error) {
	var v ThreadRealtimeStartedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/realtime/started params: %w", err)
	}
	return &v, nil
}

// ThreadRealtimeItemAddedParams unmarshals params for method "thread/realtime/itemAdded".
func (m *ServerNotification) ThreadRealtimeItemAddedParams() (*ThreadRealtimeItemAddedNotification, error) {
	var v ThreadRealtimeItemAddedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/realtime/itemAdded params: %w", err)
	}
	return &v, nil
}

// ThreadRealtimeOutputAudioDeltaParams unmarshals params for method "thread/realtime/outputAudio/delta".
func (m *ServerNotification) ThreadRealtimeOutputAudioDeltaParams() (*ThreadRealtimeOutputAudioDeltaNotification, error) {
	var v ThreadRealtimeOutputAudioDeltaNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/realtime/outputAudio/delta params: %w", err)
	}
	return &v, nil
}

// ThreadRealtimeErrorParams unmarshals params for method "thread/realtime/error".
func (m *ServerNotification) ThreadRealtimeErrorParams() (*ThreadRealtimeErrorNotification, error) {
	var v ThreadRealtimeErrorNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/realtime/error params: %w", err)
	}
	return &v, nil
}

// ThreadRealtimeClosedParams unmarshals params for method "thread/realtime/closed".
func (m *ServerNotification) ThreadRealtimeClosedParams() (*ThreadRealtimeClosedNotification, error) {
	var v ThreadRealtimeClosedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal thread/realtime/closed params: %w", err)
	}
	return &v, nil
}

// WindowsWorldWritableWarningParams unmarshals params for method "windows/worldWritableWarning".
func (m *ServerNotification) WindowsWorldWritableWarningParams() (*WindowsWorldWritableWarningNotification, error) {
	var v WindowsWorldWritableWarningNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal windows/worldWritableWarning params: %w", err)
	}
	return &v, nil
}

// WindowsSandboxSetupCompletedParams unmarshals params for method "windowsSandbox/setupCompleted".
func (m *ServerNotification) WindowsSandboxSetupCompletedParams() (*WindowsSandboxSetupCompletedNotification, error) {
	var v WindowsSandboxSetupCompletedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal windowsSandbox/setupCompleted params: %w", err)
	}
	return &v, nil
}

// AccountLoginCompletedParams unmarshals params for method "account/login/completed".
func (m *ServerNotification) AccountLoginCompletedParams() (*AccountLoginCompletedNotification, error) {
	var v AccountLoginCompletedNotification
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal account/login/completed params: %w", err)
	}
	return &v, nil
}

// ServerRequest Request initiated from the server and sent to the client.
type ServerRequest struct {
	ID     RequestID       `json:"id"`
	Method string          `json:"method"`
	Params json.RawMessage `json:"params,omitempty"`
}

// ItemCommandExecutionRequestApprovalParams unmarshals params for method "item/commandExecution/requestApproval".
func (m *ServerRequest) ItemCommandExecutionRequestApprovalParams() (*CommandExecutionRequestApprovalParams, error) {
	var v CommandExecutionRequestApprovalParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal item/commandExecution/requestApproval params: %w", err)
	}
	return &v, nil
}

// ItemFileChangeRequestApprovalParams unmarshals params for method "item/fileChange/requestApproval".
func (m *ServerRequest) ItemFileChangeRequestApprovalParams() (*FileChangeRequestApprovalParams, error) {
	var v FileChangeRequestApprovalParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal item/fileChange/requestApproval params: %w", err)
	}
	return &v, nil
}

// ItemToolRequestUserInputParams unmarshals params for method "item/tool/requestUserInput".
func (m *ServerRequest) ItemToolRequestUserInputParams() (*ToolRequestUserInputParams, error) {
	var v ToolRequestUserInputParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal item/tool/requestUserInput params: %w", err)
	}
	return &v, nil
}

// ItemToolCallParams unmarshals params for method "item/tool/call".
func (m *ServerRequest) ItemToolCallParams() (*DynamicToolCallParams, error) {
	var v DynamicToolCallParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal item/tool/call params: %w", err)
	}
	return &v, nil
}

// AccountChatgptAuthTokensRefreshParams unmarshals params for method "account/chatgptAuthTokens/refresh".
func (m *ServerRequest) AccountChatgptAuthTokensRefreshParams() (*ChatgptAuthTokensRefreshParams, error) {
	var v ChatgptAuthTokensRefreshParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal account/chatgptAuthTokens/refresh params: %w", err)
	}
	return &v, nil
}

// ApplyPatchApprovalParams unmarshals params for method "applyPatchApproval".
func (m *ServerRequest) ApplyPatchApprovalParams() (*ApplyPatchApprovalParams, error) {
	var v ApplyPatchApprovalParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal applyPatchApproval params: %w", err)
	}
	return &v, nil
}

// ExecCommandApprovalParams unmarshals params for method "execCommandApproval".
func (m *ServerRequest) ExecCommandApprovalParams() (*ExecCommandApprovalParams, error) {
	var v ExecCommandApprovalParams
	if err := json.Unmarshal(m.Params, &v); err != nil {
		return nil, fmt.Errorf("unmarshal execCommandApproval params: %w", err)
	}
	return &v, nil
}
